// SPDX-License-Identifier: MIT
#pragma once
#include <windows.h>
#include <shellapi.h>
#include <shlobj.h>
#include <filesystem>
#include <string>
#include <vector>
#include "overlay_icon.h"
namespace arrows {
inline constexpr wchar_t ShellKey[]=L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Icons";
inline constexpr wchar_t BackupKey[]=L"Software\\TidyDesk\\ArrowSettingBackup";
struct Value {bool exists=false;DWORD type=REG_SZ;std::wstring text;};
inline bool Equal(const Value& a,const Value& b){return a.exists==b.exists&&(!a.exists||(a.type==b.type&&a.text==b.text));}
inline DWORD Read(HKEY root,const wchar_t* key,const wchar_t* name,Value& value){value={};HKEY k=nullptr;auto e=RegOpenKeyExW(root,key,0,KEY_QUERY_VALUE|KEY_WOW64_64KEY,&k);if(e==ERROR_FILE_NOT_FOUND)return 0;if(e)return e;DWORD type=0,bytes=0;e=RegQueryValueExW(k,name,nullptr,&type,nullptr,&bytes);if(e==ERROR_FILE_NOT_FOUND){RegCloseKey(k);return 0;}if(e||bytes>65536||(type!=REG_SZ&&type!=REG_EXPAND_SZ)||bytes%2){RegCloseKey(k);return e?e:ERROR_INVALID_DATA;}std::vector<wchar_t> data(bytes/2+1);e=RegQueryValueExW(k,name,nullptr,&type,reinterpret_cast<BYTE*>(data.data()),&bytes);RegCloseKey(k);if(e)return e;value={true,type,std::wstring(data.data())};return 0;}
inline std::filesystem::path IconPath(){PWSTR p=nullptr;if(FAILED(SHGetKnownFolderPath(FOLDERID_LocalAppData,0,nullptr,&p)))return {};std::filesystem::path path(p);CoTaskMemFree(p);return path/L"TidyDesk"/L"Assets"/L"shortcut-overlay-v4.ico";}
inline Value HiddenValue(){return {true,REG_SZ,IconPath().wstring()+L",0"};}
inline DWORD Put(HKEY key,const wchar_t* name,DWORD type,const void* data,DWORD bytes){return RegSetValueExW(key,name,0,type,static_cast<const BYTE*>(data),bytes);}
inline DWORD SaveBackup(const Value& original,const wchar_t* key=BackupKey){HKEY k=nullptr;auto e=RegCreateKeyExW(HKEY_CURRENT_USER,key,0,nullptr,0,KEY_WRITE,nullptr,&k,nullptr);if(e)return e;DWORD exists=original.exists?1U:0U,one=1;
 e=Put(k,L"Exists",REG_DWORD,&exists,sizeof(exists));if(!e)e=Put(k,L"Type",REG_DWORD,&original.type,sizeof(original.type));if(!e)e=Put(k,L"Original",REG_SZ,original.text.c_str(),static_cast<DWORD>((original.text.size()+1)*sizeof(wchar_t)));if(!e)e=Put(k,L"Saved",REG_DWORD,&one,sizeof(one));if(!e)e=RegFlushKey(k);RegCloseKey(k);return e;}
inline DWORD LoadBackup(Value& original,bool& saved,const wchar_t* key=BackupKey){saved=false;DWORD marker=0,bytes=sizeof(marker);auto e=RegGetValueW(HKEY_CURRENT_USER,key,L"Saved",RRF_RT_REG_DWORD,nullptr,&marker,&bytes);if(e==ERROR_FILE_NOT_FOUND)return 0;if(e)return e;if(marker!=1)return ERROR_INVALID_DATA;DWORD exists=0,type=0;bytes=sizeof(exists);e=RegGetValueW(HKEY_CURRENT_USER,key,L"Exists",RRF_RT_REG_DWORD,nullptr,&exists,&bytes);if(e)return e;bytes=sizeof(type);e=RegGetValueW(HKEY_CURRENT_USER,key,L"Type",RRF_RT_REG_DWORD,nullptr,&type,&bytes);if(e)return e;if(exists>1||(type!=REG_SZ&&type!=REG_EXPAND_SZ))return ERROR_INVALID_DATA;Value text;e=Read(HKEY_CURRENT_USER,key,L"Original",text);if(e||!text.exists)return e?e:ERROR_INVALID_DATA;original={exists!=0,type,text.text};saved=true;return 0;}
// Legacy backups are read only. Their service is never used to apply a new setting.
inline DWORD Legacy(const Value& current,Value& original,bool& owned){owned=false;constexpr auto key=L"SOFTWARE\\TidyDesk\\ArrowBackup";Value owner;auto e=Read(HKEY_LOCAL_MACHINE,key,L"Owned",owner);if(e)return e;if(!current.exists||!owner.exists||current.text!=owner.text)return 0;DWORD saved=0,bytes=sizeof(saved);e=RegGetValueW(HKEY_LOCAL_MACHINE,key,L"Saved",RRF_RT_REG_DWORD|RRF_SUBKEY_WOW6464KEY,nullptr,&saved,&bytes);if(e||saved!=1)return e?e:ERROR_INVALID_DATA;DWORD exists=0,type=0;bytes=sizeof(exists);e=RegGetValueW(HKEY_LOCAL_MACHINE,key,L"Exists",RRF_RT_REG_DWORD|RRF_SUBKEY_WOW6464KEY,nullptr,&exists,&bytes);if(e)return e;if(!exists){original={};owned=true;return 0;}bytes=sizeof(type);e=RegGetValueW(HKEY_LOCAL_MACHINE,key,L"Type",RRF_RT_REG_DWORD|RRF_SUBKEY_WOW6464KEY,nullptr,&type,&bytes);if(e||!(type==REG_SZ||type==REG_EXPAND_SZ))return e?e:ERROR_INVALID_DATA;bytes=0;e=RegGetValueW(HKEY_LOCAL_MACHINE,key,L"Data",RRF_RT_REG_BINARY|RRF_SUBKEY_WOW6464KEY,nullptr,nullptr,&bytes);if(e||bytes>65536||bytes%2)return e?e:ERROR_INVALID_DATA;std::vector<wchar_t> data(bytes/2+1);e=RegGetValueW(HKEY_LOCAL_MACHINE,key,L"Data",RRF_RT_REG_BINARY|RRF_SUBKEY_WOW6464KEY,nullptr,data.data(),&bytes);if(e)return e;original={true,type,std::wstring(data.data())};owned=true;return 0;}
inline bool Hidden(bool& known){Value current,original;auto e=Read(HKEY_LOCAL_MACHINE,ShellKey,L"29",current);known=!e;if(e)return false;if(Equal(current,HiddenValue()))return true;bool legacy=false;e=Legacy(current,original,legacy);known=!e;return !e&&legacy;}
inline std::wstring Quote(const std::wstring& text){std::wstring out=L"\"";size_t slashes=0;for(auto ch:text){if(ch==L'\\'){++slashes;continue;}out.append(ch==L'\"'?slashes*2+1:slashes,L'\\');slashes=0;out+=ch;}out.append(slashes*2,L'\\');return out+L"\"";}
inline std::wstring Arguments(const Value& value){const std::wstring key=L"HKLM\\"+std::wstring(ShellKey);if(!value.exists)return L"delete "+Quote(key)+L" /v 29 /f /reg:64";return L"add "+Quote(key)+L" /v 29 /t "+(value.type==REG_EXPAND_SZ?L"REG_EXPAND_SZ":L"REG_SZ")+L" /d "+Quote(value.text)+L" /f /reg:64";}
// The elevated image and working directory are the OS-protected System32 paths.
// Only reg.exe's fixed Shell Icons\\29 add/delete operation is constructed here.
// No shell, script, user-writable executable, service, or arbitrary key is accepted.
inline DWORD WriteSystem(HWND owner,const Value& value){wchar_t directory[MAX_PATH]{};auto n=GetSystemDirectoryW(directory,MAX_PATH);if(!n||n>=MAX_PATH)return ERROR_PATH_NOT_FOUND;auto executable=std::filesystem::path(directory)/L"reg.exe";auto args=Arguments(value);SHELLEXECUTEINFOW execute{sizeof(execute)};execute.fMask=SEE_MASK_NOCLOSEPROCESS|SEE_MASK_NOASYNC;execute.hwnd=owner;execute.lpVerb=L"runas";execute.lpFile=executable.c_str();execute.lpParameters=args.c_str();execute.lpDirectory=directory;execute.nShow=SW_HIDE;if(!ShellExecuteExW(&execute))return GetLastError();if(!execute.hProcess)return ERROR_INVALID_HANDLE;auto wait=WaitForSingleObject(execute.hProcess,INFINITE);DWORD code=1;bool okay=wait==WAIT_OBJECT_0&&GetExitCodeProcess(execute.hProcess,&code);CloseHandle(execute.hProcess);return !okay?ERROR_GEN_FAILURE:code?ERROR_WRITE_FAULT:ERROR_SUCCESS;}
inline DWORD Apply(HWND owner,bool hide){Value current,original;auto e=Read(HKEY_LOCAL_MACHINE,ShellKey,L"29",current);if(e)return e;bool saved=false;e=LoadBackup(original,saved);if(e)return e;const auto hidden=HiddenValue();if(hidden.text==L",0")return ERROR_PATH_NOT_FOUND;
 if(!saved){bool legacy=false;e=Legacy(current,original,legacy);if(e)return e;if(!legacy)original=current;if(!hide&&!legacy)return current.exists?ERROR_NOT_SUPPORTED:ERROR_SUCCESS;e=SaveBackup(original);if(e)return e;}
 // A previous cancelled request can be retried, but unrelated subsequent changes stop us.
 Value legacyOriginal;bool legacy=false;e=Legacy(current,legacyOriginal,legacy);if(e)return e;if(!Equal(current,hidden)&&!Equal(current,original)&&!legacy)return ERROR_REVISION_MISMATCH;
 auto desired=hide?hidden:original;if(hide){auto icon=IconPath();std::error_code ec;std::filesystem::create_directories(icon.parent_path(),ec);if(ec)return ERROR_PATH_NOT_FOUND;if(!overlay::Verify(icon)){auto temp=icon;temp+=L".tmp";if(!overlay::Write(temp)||!overlay::Verify(temp)||!MoveFileExW(temp.c_str(),icon.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))return ERROR_WRITE_FAULT;}}
 Value check;e=Read(HKEY_LOCAL_MACHINE,ShellKey,L"29",check);if(e)return e;if(!Equal(current,check))return ERROR_REVISION_MISMATCH;if(!Equal(current,desired)){e=WriteSystem(owner,desired);if(e)return e;}e=Read(HKEY_LOCAL_MACHINE,ShellKey,L"29",check);if(e)return e;if(!Equal(check,desired))return ERROR_WRITE_FAULT;if(!hide){HKEY key=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,BackupKey,0,KEY_SET_VALUE,&key)==0){RegDeleteValueW(key,L"Saved");RegCloseKey(key);}}return 0;
}
inline int Test(){for(auto text:{std::wstring(L"C:\\中文 空格\\blank.ico,0"),std::wstring(L"\"C:\\icons\\a.ico\",0"),std::wstring(L"%SystemRoot%\\icons.dll,-1"),std::wstring(L"tail\\"),std::wstring(L"x\" /v Bad /d \"y")}){Value v{true,REG_SZ,text};int argc=0;auto argv=CommandLineToArgvW((L"reg.exe "+Arguments(v)).c_str(),&argc);bool okay=argv&&argc==11&&std::wstring(argv[1])==L"add"&&std::wstring(argv[2])==L"HKLM\\"+std::wstring(ShellKey)&&std::wstring(argv[4])==L"29"&&std::wstring(argv[8])==text;if(argv)LocalFree(argv);if(!okay)return 1;}
 auto key=L"Software\\TidyDeskArrowTest-"+std::to_wstring(GetCurrentProcessId());int result=0;for(Value original:{Value{},Value{true,REG_EXPAND_SZ,L"%SystemRoot%\\original.ico,0"}}){Value loaded;bool saved=false;if(SaveBackup(original,key.c_str())||LoadBackup(loaded,saved,key.c_str())||!saved||!Equal(original,loaded))result=2;}RegDeleteTreeW(HKEY_CURRENT_USER,key.c_str());return result;}
}
