// SPDX-License-Identifier: MIT
#include "desktop_model.h"
#include "desktop_geometry.h"
#include "desktop_animation.h"
#include "shell_icon.h"
#include <commctrl.h>
#include <windowsx.h>
#include <shellapi.h>
#include <shlobj.h>
#include <gdiplus.h>
#include <wrl/client.h>
#include <thread>
#include <atomic>
#include <memory>
#include <set>
#include <algorithm>
#include <fstream>
using Microsoft::WRL::ComPtr;
using namespace Gdiplus;
namespace {
constexpr UINT Refresh=WM_APP+2, Loaded=WM_APP+3, NewCollection=WM_APP+5;
constexpr wchar_t FrameClass[]=L"TidyDesk.Desktop.Frame";
struct Item {std::wstring path,name,label;std::vector<BYTE> pixels;};
struct Batch {std::vector<Item> items;};
struct Frame;
std::vector<std::unique_ptr<Frame>> frames;
HWND controller=nullptr,desktop=nullptr,shade=nullptr;
Frame* expanded=nullptr;
UINT shellMessage=0;
bool rebuilding=false;
unsigned interaction=0;
struct Interact {Interact(){++interaction;}~Interact(){--interaction;}};
void Paint(Frame* f);
void Expand(Frame* f,bool value,bool animate=true);
void Persist();
void Rebuild();
void MenuCommand(Frame* f,int cmd);
// Reused only during a transition; released immediately on completion.
struct MotionSurface {
 HDC dc=nullptr;HBITMAP dib=nullptr;HGDIOBJ previous=nullptr;void* pixels=nullptr;int width=0,height=0;
 void Clear(){if(dc&&previous)SelectObject(dc,previous);if(dib)DeleteObject(dib);if(dc)DeleteDC(dc);dc=nullptr;dib=nullptr;previous=nullptr;pixels=nullptr;width=height=0;}
 ~MotionSurface(){Clear();}
 bool Make(int w,int h){if(dc&&width>=w&&height>=h)return true;Clear();HDC screen=GetDC(nullptr);dc=CreateCompatibleDC(screen);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=w;info.bmiHeader.biHeight=-h;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;if(dc)dib=CreateDIBSection(screen,&info,DIB_RGB_COLORS,&pixels,nullptr,0);ReleaseDC(nullptr,screen);if(!dc||!dib){Clear();return false;}previous=SelectObject(dc,dib);width=w;height=h;return true;}
};
struct Frame {
 desk::Box box;HWND window=nullptr;std::unique_ptr<Batch> content=std::make_unique<Batch>();
 std::set<int> selected;int scroll=0;bool hover=false,buttonHover=false,dropHover=false,large=false,pressed=false,dragging=false,painted=false,hitSurface=false;
 bool animating=false,testAnimation=false;double animationStart=0,animationDuration=220,animationProgress=0,fromInset=3,fromShade=0;RECT animationFrom{},animationTo{};
 std::unique_ptr<Bitmap> contentFrom,contentTo;MotionSurface surface;
 double Inset()const{return animating?fromInset+((large?13.0:3.0)-fromInset)*animationProgress:(large?13.0:3.0);}
 double ShadeOpacity()const{return animating?fromShade+((large?60.0:0.0)-fromShade)*animationProgress:(large?60.0:0.0);}

 POINT press{};RECT saved{};ULONGLONG entered=0;int wheel=0;
 ComPtr<IContextMenu2> menu2;ComPtr<IContextMenu3> menu3;
 HANDLE cancel=CreateEventW(nullptr,TRUE,FALSE,nullptr);std::thread watcher,loader;std::atomic<bool> busy{false};bool again=false;
 ~Frame(){if(animating&&interaction)--interaction;SetEvent(cancel);if(watcher.joinable())watcher.join();if(loader.joinable())loader.join();
  if(window){MSG m{};while(PeekMessageW(&m,window,Loaded,Loaded,PM_REMOVE))delete reinterpret_cast<Batch*>(m.lParam);if(IsWindow(window))DestroyWindow(window);}CloseHandle(cancel);}
 int D(int v)const{return MulDiv(v,static_cast<int>(GetDpiForWindow(window)),96);}
 desk::Grid GridAt(int width,int height)const{auto g=desk::Grid::Make(MulDiv(width,96,static_cast<int>(GetDpiForWindow(window))),MulDiv(height,96,static_cast<int>(GetDpiForWindow(window))),static_cast<int>(box.size));g.cellWidth=D(g.cellWidth);g.cellHeight=D(g.cellHeight);g.top=D(g.top);g.left=D(g.left);return g;}
 desk::Grid Grid()const{RECT r{};GetClientRect(window,&r);return GridAt(r.right,r.bottom);}
 int Hit(POINT p)const{if(animating)return -1;auto dpi=static_cast<int>(GetDpiForWindow(window));RECT r{};GetClientRect(window,&r);auto grid=desk::Grid::Make(MulDiv(r.right,96,dpi),MulDiv(r.bottom,96,dpi),static_cast<int>(box.size));return box.collapsed?-1:grid.ItemHit(MulDiv(p.x,96,dpi),MulDiv(p.y,96,dpi),scroll,static_cast<int>(content->items.size()),static_cast<int>(box.size));}
 RECT Button()const{RECT r{};GetClientRect(window,&r);double progress=(Inset()-3.0)/10.0;int left=D(42)+static_cast<int>(D(11)*progress),right=D(10)+static_cast<int>(D(11)*progress),top=D(16)+static_cast<int>(D(5)*progress);return {r.right-left,top,r.right-right,top+D(28)};}
 void Scan(){if(busy.exchange(true)){again=true;return;}if(loader.joinable())loader.join();auto path=box.path;auto target=window;auto stop=cancel;
  loader=std::thread([path,target,stop](){CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);auto batch=std::make_unique<Batch>();std::error_code ec;
   for(const auto& entry:std::filesystem::directory_iterator(path,ec)){if(WaitForSingleObject(stop,0)==WAIT_OBJECT_0)break;auto attrs=GetFileAttributesW(entry.path().c_str());if(attrs==INVALID_FILE_ATTRIBUTES||(attrs&(FILE_ATTRIBUTE_HIDDEN|FILE_ATTRIBUTE_SYSTEM)))continue;
    Item i;i.path=entry.path().wstring();i.name=entry.path().filename().wstring();i.label=i.name;if(_wcsicmp(entry.path().extension().c_str(),L".lnk")==0||_wcsicmp(entry.path().extension().c_str(),L".url")==0)i.label=entry.path().stem().wstring();
    if(batch->items.size()<512){if(auto icon=desk::CollectionIcon(i.path)){i.pixels=desk::IconPixels(icon,64);DestroyIcon(icon);}}
    batch->items.push_back(std::move(i));}
   if(WaitForSingleObject(stop,0)!=WAIT_OBJECT_0&&PostMessageW(target,Loaded,0,reinterpret_cast<LPARAM>(batch.get())))batch.release();CoUninitialize();});}
 void Watch(){auto path=box.path;watcher=std::thread([this,path](){HANDLE change=FindFirstChangeNotificationW(path.c_str(),FALSE,FILE_NOTIFY_CHANGE_FILE_NAME|FILE_NOTIFY_CHANGE_DIR_NAME|FILE_NOTIFY_CHANGE_LAST_WRITE|FILE_NOTIFY_CHANGE_ATTRIBUTES);if(change==INVALID_HANDLE_VALUE)return;HANDLE handles[]={cancel,change};while(WaitForMultipleObjects(2,handles,FALSE,INFINITE)==WAIT_OBJECT_0+1){PostMessageW(window,Refresh,0,0);if(!FindNextChangeNotification(change))break;}FindCloseChangeNotification(change);});}
};
void Persist(){if(rebuilding)return;auto boxes=desk::Load();for(auto& box:boxes)for(auto& f:frames)if(box.id==f->box.id)box=f->box;if(!desk::Save(boxes))MessageBoxW(controller,L"布局保存失败。文件仍保留在原文件夹。",L"TidyDesk",MB_OK|MB_ICONWARNING);}
void Rounded(GraphicsPath& p,REAL x,REAL y,REAL w,REAL h,REAL radius){REAL d=radius*2;p.AddArc(x,y,d,d,180,90);p.AddArc(x+w-d,y,d,d,270,90);p.AddArc(x+w-d,y+h-d,d,d,0,90);p.AddArc(x,y+h-d,d,d,90,90);p.CloseFigure();}
void Text(Graphics& g,const std::wstring& text,RectF r,REAL size,bool symbol=false){
 FontFamily family(symbol?L"Segoe MDL2 Assets":L"Microsoft YaHei UI");StringFormat format;format.SetAlignment(StringAlignmentCenter);format.SetLineAlignment(StringAlignmentCenter);format.SetTrimming(StringTrimmingEllipsisCharacter);
 GraphicsPath path;path.AddString(text.c_str(),-1,&family,FontStyleRegular,size,r,&format);
 Pen outline(Color(150,15,20,30),2.0f);outline.SetLineJoin(LineJoinRound);SolidBrush ink(Color(245,245,247,250));g.DrawPath(&outline,&path);g.FillPath(&ink,&path);
}
void DrawItems(Graphics& g,Frame* f,int width,int height){REAL scale=static_cast<REAL>(f->D(100))/100.0f;
  if(!f->box.collapsed){auto grid=f->GridAt(width,height);int scroll=std::clamp(f->scroll,0,grid.MaxScroll(static_cast<int>(f->content->items.size())));g.SetClip(Rect(8,f->D(46),width-16,(std::max)(1,height-f->D(54))));
   for(int row=0;row<grid.rows;++row)for(int col=0;col<grid.columns;++col){int index=(row+scroll)*grid.columns+col;if(index>=static_cast<int>(f->content->items.size()))break;auto& item=f->content->items[static_cast<size_t>(index)];int x=grid.left+col*grid.cellWidth,y=grid.top+row*grid.cellHeight;
    if(f->selected.count(index)){GraphicsPath selection;Rounded(selection,static_cast<REAL>(x),static_cast<REAL>(y-2),static_cast<REAL>(grid.cellWidth-4),static_cast<REAL>(grid.cellHeight-5),5*scale);SolidBrush fill(Color(55,190,215,240));g.FillPath(&fill,&selection);}
    if(!item.pixels.empty()){Bitmap icon(64,64,64*4,PixelFormat32bppPARGB,item.pixels.data());int size=f->D(static_cast<int>(f->box.size));g.DrawImage(&icon,x+(grid.cellWidth-size)/2,y,size,size);}
    Text(g,item.label,RectF(static_cast<REAL>(x+2),static_cast<REAL>(y+f->D(static_cast<int>(f->box.size))+4),static_cast<REAL>(grid.cellWidth-8),34*scale),12*scale);
   }
  }
}
void DrawCached(Graphics& g,Bitmap* image,double opacity){if(!image||opacity<=0)return;ColorMatrix matrix{};for(int i=0;i<5;++i)matrix.m[i][i]=1.0f;matrix.m[3][3]=static_cast<REAL>(opacity);ImageAttributes attributes;attributes.SetColorMatrix(&matrix);int width=static_cast<int>(image->GetWidth()),height=static_cast<int>(image->GetHeight());g.DrawImage(image,Rect(0,0,width,height),0,0,width,height,UnitPixel,&attributes);}
std::unique_ptr<Bitmap> CacheItems(Frame* f,int width,int height,bool current){auto image=std::make_unique<Bitmap>(width,height,PixelFormat32bppPARGB);if(image->GetLastStatus()!=Ok)return {};Graphics g(image.get());g.Clear(Color(0,0,0,0));g.SetSmoothingMode(SmoothingModeAntiAlias);g.SetTextRenderingHint(TextRenderingHintAntiAliasGridFit);if(current&&f->animating&&f->contentFrom&&f->contentTo){DrawCached(g,f->contentFrom.get(),1.0-f->animationProgress);DrawCached(g,f->contentTo.get(),f->animationProgress);}else DrawItems(g,f,width,height);return image;}
void Paint(Frame* f){if(!f->window||!IsWindow(f->window))return;RECT r{};GetClientRect(f->window,&r);int width=r.right,height=r.bottom;if(width<1||height<1)return;
 MotionSurface temporary;auto& surface=f->animating?f->surface:temporary;if(!surface.Make(width,height))return;HDC screen=GetDC(nullptr),dc=surface.dc;void* pixels=surface.pixels;

 {Bitmap bitmap(width,height,surface.width*4,PixelFormat32bppPARGB,static_cast<BYTE*>(pixels));Graphics g(&bitmap);g.Clear(Color(1,0,0,0));g.SetSmoothingMode(SmoothingModeAntiAlias);g.SetTextRenderingHint(TextRenderingHintAntiAliasGridFit);
  REAL scale=static_cast<REAL>(f->D(100))/100.0f;GraphicsPath border;REAL inset=static_cast<REAL>(f->Inset())*scale;Rounded(border,inset,13*scale,static_cast<REAL>(width)-2*inset,static_cast<REAL>(height)-13*scale-inset,16*scale);
  // A 1/255 alpha hit surface keeps empty space droppable without an opaque panel.
  SolidBrush hit(Color(1,0,0,0));g.FillPath(&hit,&border);
  REAL titleWidth=(std::min)(static_cast<REAL>(width)-110*scale,static_cast<REAL>(f->box.name.size())*17*scale+24*scale);
  auto clip=g.Save();g.ExcludeClip(RectF((static_cast<REAL>(width)-titleWidth)/2,0,titleWidth,25*scale));Pen line(Color(f->dropHover?200:f->hover||f->large?135:100,220,230,239),scale);g.DrawPath(&line,&border);g.Restore(clip);
  Text(g,f->box.name,RectF((static_cast<REAL>(width)-titleWidth)/2,0,titleWidth,26*scale),16*scale);
  if(f->hover||f->large||f->animating||f->box.collapsed){RECT b=f->Button();POINT cursor{};GetCursorPos(&cursor);ScreenToClient(f->window,&cursor);if(PtInRect(&b,cursor)){GraphicsPath button;Rounded(button,static_cast<REAL>(b.left),static_cast<REAL>(b.top),static_cast<REAL>(b.right-b.left),static_cast<REAL>(b.bottom-b.top),6*scale);SolidBrush fill(Color(40,240,245,250));g.FillPath(&fill,&button);}Text(g,f->large?L"\xE73F":L"\xE740",RectF(static_cast<REAL>(b.left),static_cast<REAL>(b.top),static_cast<REAL>(b.right-b.left),static_cast<REAL>(b.bottom-b.top)),16*scale,true);}
  if(f->animating&&f->contentFrom&&f->contentTo){auto state=g.Save();g.SetClip(Rect(8,f->D(46),width-16,(std::max)(1,height-f->D(54))));DrawCached(g,f->contentFrom.get(),1.0-f->animationProgress);DrawCached(g,f->contentTo.get(),f->animationProgress);g.Restore(state);}else DrawItems(g,f,width,height);

 }
 f->hitSurface=true;if(!f->animating)for(size_t pixel=0;pixel<static_cast<size_t>(width)*height;++pixel)if((static_cast<DWORD*>(pixels)[pixel]>>24)==0){f->hitSurface=false;break;}
 POINT origin{};SIZE size{width,height};BLENDFUNCTION blend{AC_SRC_OVER,0,255,AC_SRC_ALPHA};f->painted=UpdateLayeredWindow(f->window,screen,nullptr,&size,dc,&origin,0,&blend,ULW_ALPHA)!=FALSE;ReleaseDC(nullptr,screen);
}
void HideShade(){if(shade){DestroyWindow(shade);shade=nullptr;}}
LRESULT CALLBACK ShadeProc(HWND w,UINT m,WPARAM wp,LPARAM lp){if(m==WM_LBUTTONDOWN||m==WM_RBUTTONDOWN||m==WM_KEYDOWN){if(expanded)Expand(expanded,false);return 0;}if(m==WM_ERASEBKGND){RECT r{};GetClientRect(w,&r);FillRect(reinterpret_cast<HDC>(wp),&r,static_cast<HBRUSH>(GetStockObject(BLACK_BRUSH)));return 1;}return DefWindowProcW(w,m,wp,lp);}
void ShadeBounds(Frame* f,const RECT& rect){if(!shade)return;RECT backdrop{};GetWindowRect(shade,&backdrop);auto region=CreateRectRgn(0,0,backdrop.right-backdrop.left,backdrop.bottom-backdrop.top);auto hole=CreateRoundRectRgn(rect.left-backdrop.left,rect.top-backdrop.top,rect.right-backdrop.left,rect.bottom-backdrop.top,f->D(32),f->D(32));CombineRgn(region,region,hole,RGN_DIFF);DeleteObject(hole);if(!SetWindowRgn(shade,region,TRUE))DeleteObject(region);SetLayeredWindowAttributes(shade,0,static_cast<BYTE>(std::clamp(f->ShadeOpacity(),0.0,60.0)),LWA_ALPHA);}
void FinishAnimation(Frame* f){KillTimer(f->window,6);f->animationProgress=1;auto end=f->animationTo;
 if(!f->large){HideShade();if(expanded==f)expanded=nullptr;SetWindowLongPtrW(f->window,GWLP_HWNDPARENT,reinterpret_cast<LONG_PTR>(desktop));SetWindowLongPtrW(f->window,GWL_STYLE,WS_POPUP|WS_VISIBLE|WS_THICKFRAME);SetWindowPos(f->window,HWND_NOTOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE);SetWindowPos(f->window,HWND_BOTTOM,end.left,end.top,end.right-end.left,end.bottom-end.top,SWP_NOACTIVATE|SWP_FRAMECHANGED);}
 else{SetWindowPos(f->window,nullptr,end.left,end.top,end.right-end.left,end.bottom-end.top,SWP_NOZORDER|SWP_NOACTIVATE);ShadeBounds(f,end);}
 if(f->animating&&interaction)--interaction;f->animating=false;f->contentFrom.reset();f->contentTo.reset();f->surface.Clear();f->scroll=std::clamp(f->scroll,0,f->Grid().MaxScroll(static_cast<int>(f->content->items.size())));Paint(f);
}
void AnimationStep(Frame* f){if(!f->animating)return;double t=std::clamp((desk::motion::Milliseconds()-f->animationStart)/f->animationDuration,0.0,1.0);f->animationProgress=desk::motion::Ease(t);auto rect=desk::motion::Bounds(f->animationFrom,f->animationTo,f->animationProgress);SetWindowPos(f->window,nullptr,rect.left,rect.top,rect.right-rect.left,rect.bottom-rect.top,SWP_NOZORDER|SWP_NOACTIVATE);ShadeBounds(f,rect);Paint(f);if(t>=1.0)FinishAnimation(f);}
void Expand(Frame* f,bool value,bool animate){if(value==f->large){if(!animate&&f->animating)FinishAnimation(f);return;}if(value&&expanded&&expanded!=f)Expand(expanded,false,false);
 RECT from{};GetWindowRect(f->window,&from);double inset=f->Inset(),opacity=f->ShadeOpacity();BOOL enabled=TRUE;SystemParametersInfoW(SPI_GETCLIENTAREAANIMATION,0,&enabled,0);bool transition=animate&&(enabled||f->testAnimation);auto source=transition?CacheItems(f,from.right-from.left,from.bottom-from.top,true):nullptr;
 if(f->animating){KillTimer(f->window,6);if(interaction)--interaction;}f->animating=true;++interaction;f->animationProgress=0;f->fromInset=inset;f->fromShade=opacity;f->animationFrom=from;f->large=value;f->box.collapsed=false;
 if(value){f->saved=from;expanded=f;MONITORINFO monitor{sizeof(monitor)};GetMonitorInfoW(MonitorFromWindow(f->window,MONITOR_DEFAULTTONEAREST),&monitor);auto area=monitor.rcWork;int width=(std::min)(f->D(940),static_cast<int>(area.right-area.left)-f->D(48)),height=(std::min)(f->D(540),static_cast<int>(area.bottom-area.top)-f->D(64));int x=area.left+(area.right-area.left-width)/2,y=area.top+(area.bottom-area.top-height)/2;f->animationTo={x,y,x+width,y+height};
  if(!shade){auto backdrop=monitor.rcMonitor;shade=CreateWindowExW(WS_EX_TOOLWINDOW|WS_EX_LAYERED,L"TidyDesk.Desktop.Shade",L"",WS_POPUP,backdrop.left,backdrop.top,backdrop.right-backdrop.left,backdrop.bottom-backdrop.top,controller,nullptr,GetModuleHandleW(nullptr),nullptr);}
  ShadeBounds(f,from);if(shade)SetWindowPos(shade,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE|SWP_SHOWWINDOW);
  SetWindowLongPtrW(f->window,GWL_STYLE,WS_POPUP|WS_VISIBLE);SetWindowLongPtrW(f->window,GWLP_HWNDPARENT,reinterpret_cast<LONG_PTR>(controller));SetWindowPos(f->window,HWND_TOPMOST,from.left,from.top,from.right-from.left,from.bottom-from.top,SWP_FRAMECHANGED|SWP_NOACTIVATE);SetForegroundWindow(f->window);SetFocus(f->window);
 }else f->animationTo={f->box.x,f->box.y,f->box.x+f->box.w,f->box.y+f->box.h};
 f->contentFrom=std::move(source);f->contentTo=transition?CacheItems(f,f->animationTo.right-f->animationTo.left,f->animationTo.bottom-f->animationTo.top,false):nullptr;
 if(!transition||!f->contentFrom||!f->contentTo){FinishAnimation(f);return;}if(!f->surface.Make((std::max)(from.right-from.left,f->animationTo.right-f->animationTo.left),(std::max)(from.bottom-from.top,f->animationTo.bottom-f->animationTo.top))){FinishAnimation(f);return;}f->animationStart=desk::motion::Milliseconds();f->animationDuration=value?220.0:180.0;if(!SetTimer(f->window,6,10,nullptr)){FinishAnimation(f);return;}Paint(f);
}
std::vector<std::wstring> DropPaths(IDataObject* data){std::vector<std::wstring> paths;FORMATETC fmt{CF_HDROP,nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL};STGMEDIUM medium{};if(SUCCEEDED(data->GetData(&fmt,&medium))){auto drop=static_cast<HDROP>(medium.hGlobal);UINT count=DragQueryFileW(drop,0xffffffff,nullptr,0);for(UINT i=0;i<count;++i){UINT len=DragQueryFileW(drop,i,nullptr,0);std::wstring p(len+1,L'\0');DragQueryFileW(drop,i,p.data(),len+1);p.resize(len);paths.push_back(p);}ReleaseStgMedium(&medium);}return paths;}
void Failure(HWND w,HRESULT hr){if(FAILED(hr)&&hr!=HRESULT_FROM_WIN32(ERROR_CANCELLED)){wchar_t text[160]{};swprintf_s(text,L"操作未完成（0x%08X）。文件未被静默覆盖。",static_cast<unsigned>(hr));MessageBoxW(w,text,L"TidyDesk",MB_OK|MB_ICONWARNING);}}
class DropTarget final:public IDropTarget,public IDropSource {
 LONG refs=1;Frame* f;bool accepted=false,linkOnly=false,enteredInteraction=false;
 void Leave(){f->dropHover=false;f->entered=0;if(enteredInteraction){--interaction;enteredInteraction=false;}Paint(f);}
public:
 explicit DropTarget(Frame* value):f(value){}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** out) override{if(!out)return E_POINTER;*out=nullptr;if(id==IID_IUnknown||id==IID_IDropTarget)*out=static_cast<IDropTarget*>(this);else if(id==IID_IDropSource)*out=static_cast<IDropSource*>(this);else return E_NOINTERFACE;AddRef();return S_OK;}
 ULONG STDMETHODCALLTYPE AddRef() override{return static_cast<ULONG>(InterlockedIncrement(&refs));}
 ULONG STDMETHODCALLTYPE Release() override{auto r=InterlockedDecrement(&refs);if(!r)delete this;return static_cast<ULONG>(r);}
 HRESULT STDMETHODCALLTYPE DragEnter(IDataObject* d,DWORD,POINTL,DWORD* effect) override{auto paths=DropPaths(d);accepted=!paths.empty();linkOnly=accepted;for(auto& p:paths)if(_wcsicmp(std::filesystem::path(p).extension().c_str(),L".exe"))linkOnly=false;if(!enteredInteraction){++interaction;enteredInteraction=true;}f->dropHover=accepted;f->entered=GetTickCount64();*effect=accepted?(linkOnly?DROPEFFECT_LINK:DROPEFFECT_MOVE):DROPEFFECT_NONE;Paint(f);return S_OK;}
 HRESULT STDMETHODCALLTYPE DragOver(DWORD,POINTL,DWORD* effect) override{*effect=accepted?(linkOnly?DROPEFFECT_LINK:DROPEFFECT_MOVE):DROPEFFECT_NONE;if(accepted&&!f->large&&!f->dragging&&GetTickCount64()-f->entered>650)Expand(f,true);return S_OK;}
 HRESULT STDMETHODCALLTYPE DragLeave() override{Leave();return S_OK;}
 HRESULT STDMETHODCALLTYPE Drop(IDataObject* data,DWORD,POINTL point,DWORD* effect) override{Interact guard;auto paths=DropPaths(data);*effect=DROPEFFECT_NONE;bool local=!paths.empty();for(auto& p:paths)if(_wcsicmp(std::filesystem::path(p).parent_path().c_str(),f->box.path.c_str()))local=false;
  if(local){POINT pos{point.x,point.y};ScreenToClient(f->window,&pos);int index=f->Hit(pos);std::vector<std::wstring> order;for(auto& item:f->content->items)order.push_back(item.path);if(index<0)index=static_cast<int>(order.size());for(auto& p:paths){auto it=std::find(order.begin(),order.end(),p);if(it!=order.end()){if(it-order.begin()<index)--index;order.erase(it);}}index=std::clamp(index,0,static_cast<int>(order.size()));order.insert(order.begin()+index,paths.begin(),paths.end());f->box.order.clear();for(auto& p:order)f->box.order.push_back(std::filesystem::path(p).filename().wstring());Persist();}
  else Failure(f->window,desk::Transfer(f->window,paths,f->box.path));Leave();f->Scan();return S_OK;}
 HRESULT STDMETHODCALLTYPE QueryContinueDrag(BOOL escape,DWORD keys) override{return escape?DRAGDROP_S_CANCEL:!(keys&MK_LBUTTON)?DRAGDROP_S_DROP:S_OK;}
 HRESULT STDMETHODCALLTYPE GiveFeedback(DWORD) override{return DRAGDROP_S_USEDEFAULTCURSORS;}
};
std::vector<std::wstring> Selected(Frame* f){std::vector<std::wstring> paths;for(int i:f->selected)if(i>=0&&i<static_cast<int>(f->content->items.size()))paths.push_back(f->content->items[static_cast<size_t>(i)].path);return paths;}
void DragOut(Frame* f){Interact guard;auto selected=Selected(f);if(selected.empty())return;f->dragging=true;HideShade();
 auto parent=ILCreateFromPathW(f->box.path.c_str());std::vector<PIDLIST_ABSOLUTE> full;std::vector<PCUITEMID_CHILD> children;for(auto& p:selected){auto id=ILCreateFromPathW(p.c_str());if(id){full.push_back(id);children.push_back(ILFindLastID(id));}}
 ComPtr<IDataObject> data;if(parent&&!children.empty()&&SUCCEEDED(SHCreateDataObject(parent,static_cast<UINT>(children.size()),children.data(),nullptr,IID_PPV_ARGS(&data)))){auto source=new DropTarget(f);DWORD effect=0;DoDragDrop(data.Get(),source,DROPEFFECT_MOVE|DROPEFFECT_COPY|DROPEFFECT_LINK,&effect);source->Release();}for(auto p:full)ILFree(p);ILFree(parent);f->dragging=false;if(f->large)Expand(f,false);f->Scan();}
void FileMenu(Frame* f,POINT point){Interact guard;auto paths=Selected(f);if(paths.empty())return;ComPtr<IShellFolder> folder;PCUITEMID_CHILD child=nullptr;auto first=ILCreateFromPathW(paths[0].c_str());if(!first)return;
 if(SUCCEEDED(SHBindToParent(first,IID_PPV_ARGS(&folder),&child))){std::vector<PIDLIST_ABSOLUTE> full;std::vector<PCUITEMID_CHILD> ids;for(auto& path:paths){auto id=ILCreateFromPathW(path.c_str());if(id){full.push_back(id);ids.push_back(ILFindLastID(id));}}ComPtr<IContextMenu> menu;
  if(!ids.empty()&&SUCCEEDED(folder->GetUIObjectOf(f->window,static_cast<UINT>(ids.size()),ids.data(),IID_IContextMenu,nullptr,reinterpret_cast<void**>(menu.GetAddressOf())))){menu.As(&f->menu2);menu.As(&f->menu3);auto popup=CreatePopupMenu();menu->QueryContextMenu(popup,0,1,0x7fff,CMF_NORMAL);AppendMenuW(popup,MF_SEPARATOR,0,nullptr);AppendMenuW(popup,MF_STRING,0x8001,L"重命名收纳框");AppendMenuW(popup,MF_STRING,0x8002,f->large?L"收起收纳框":L"展开收纳框");AppendMenuW(popup,MF_STRING,0x8005,L"解散收纳框…");SetForegroundWindow(f->window);int cmd=TrackPopupMenu(popup,TPM_RETURNCMD|TPM_RIGHTBUTTON,point.x,point.y,0,f->window,nullptr);if(cmd>0&&cmd<0x8000){CMINVOKECOMMANDINFOEX invoke{};invoke.cbSize=sizeof(invoke);invoke.hwnd=f->window;invoke.fMask=CMIC_MASK_UNICODE;invoke.lpVerb=MAKEINTRESOURCEA(cmd-1);invoke.lpVerbW=MAKEINTRESOURCEW(cmd-1);invoke.nShow=SW_SHOWNORMAL;Failure(f->window,menu->InvokeCommand(reinterpret_cast<CMINVOKECOMMANDINFO*>(&invoke)));}DestroyMenu(popup);f->menu2.Reset();f->menu3.Reset();if(cmd>=0x8000)MenuCommand(f,cmd-0x8000);}
  for(auto id:full)ILFree(id);
 }ILFree(first);f->Scan();}
struct NameDialog {HWND edit=nullptr;bool done=false,ok=false;std::wstring text;};
LRESULT CALLBACK NameProc(HWND w,UINT m,WPARAM wp,LPARAM lp){auto state=reinterpret_cast<NameDialog*>(GetWindowLongPtrW(w,GWLP_USERDATA));if(m==WM_NCCREATE){state=static_cast<NameDialog*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(state));}if(!state)return DefWindowProcW(w,m,wp,lp);if(m==WM_COMMAND&&(LOWORD(wp)==IDOK||LOWORD(wp)==IDCANCEL)){if(LOWORD(wp)==IDOK){wchar_t text[128]{};GetWindowTextW(state->edit,text,128);if(!*text)return 0;state->text=text;state->ok=true;}state->done=true;return 0;}if(m==WM_CLOSE){state->done=true;return 0;}return DefWindowProcW(w,m,wp,lp);}
bool Rename(HWND owner,std::wstring& name){Interact guard;NameDialog state;state.text=name;auto d=[&](int v){return MulDiv(v,static_cast<int>(GetDpiForWindow(owner)),96);};RECT r{};GetWindowRect(owner,&r);MONITORINFO monitor{sizeof(monitor)};GetMonitorInfoW(MonitorFromWindow(owner,MONITOR_DEFAULTTONEAREST),&monitor);int x=std::clamp<LONG>(r.left+d(20),monitor.rcWork.left,(std::max)(monitor.rcWork.left,monitor.rcWork.right-d(360))),y=std::clamp<LONG>(r.top+d(20),monitor.rcWork.top,(std::max)(monitor.rcWork.top,monitor.rcWork.bottom-d(172)));
 HWND w=CreateWindowExW(WS_EX_DLGMODALFRAME|WS_EX_CONTROLPARENT,L"TidyDesk.Desktop.Name",L"重命名收纳框",WS_POPUP|WS_CAPTION|WS_SYSMENU,x,y,d(360),d(172),owner,nullptr,GetModuleHandleW(nullptr),&state);if(!w)return false;
 auto font=CreateFontW(-d(14),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Microsoft YaHei UI");state.edit=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",name.c_str(),WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_AUTOHSCROLL,d(16),d(18),d(312),d(32),w,reinterpret_cast<HMENU>(10),nullptr,nullptr);SendMessageW(state.edit,EM_SETLIMITTEXT,80,0);SendMessageW(state.edit,WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);
 auto okay=CreateWindowW(L"BUTTON",L"确定",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,d(152),d(76),d(82),d(32),w,reinterpret_cast<HMENU>(IDOK),nullptr,nullptr);auto cancel=CreateWindowW(L"BUTTON",L"取消",WS_CHILD|WS_VISIBLE|WS_TABSTOP,d(246),d(76),d(82),d(32),w,reinterpret_cast<HMENU>(IDCANCEL),nullptr,nullptr);SendMessageW(okay,WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);SendMessageW(cancel,WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);
 EnableWindow(owner,FALSE);ShowWindow(w,SW_SHOW);SetForegroundWindow(w);SetFocus(state.edit);SendMessageW(state.edit,EM_SETSEL,0,-1);MSG msg{};while(!state.done&&GetMessageW(&msg,nullptr,0,0)>0){if(msg.message==WM_KEYDOWN&&(msg.wParam==VK_RETURN||msg.wParam==VK_ESCAPE)){SendMessageW(w,WM_COMMAND,msg.wParam==VK_RETURN?IDOK:IDCANCEL,0);continue;}if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}EnableWindow(owner,TRUE);DestroyWindow(w);DeleteObject(font);if(state.ok)name=state.text;return state.ok;}
void RenameFrame(Frame* f){auto name=f->box.name;if(!Rename(f->window,name))return;std::wstring error;if(!desk::RenameBox(f->box.id,name,error))MessageBoxW(f->window,error.c_str(),L"无法重命名",MB_OK|MB_ICONWARNING);else{auto boxes=desk::Load();for(const auto& box:boxes)if(box.id==f->box.id)f->box=box;Paint(f);}}
void Dissolve(Frame* f){Interact guard;if(f->large)Expand(f,false);desk::Dissolve(f->window,f->box.id);}
void Menu(Frame* f,POINT p){Interact guard;auto menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,1,L"重命名\tF2");AppendMenuW(menu,MF_STRING,2,f->large?L"收起":L"展开");AppendMenuW(menu,MF_STRING,3,f->box.locked?L"解锁位置":L"锁定位置");auto sizes=CreatePopupMenu();for(int i=0;i<3;++i)AppendMenuW(sizes,MF_STRING|(f->box.size==static_cast<unsigned>(32+i*16)?MF_CHECKED:0),static_cast<UINT_PTR>(20+i),i==0?L"小":i==1?L"中":L"大");AppendMenuW(menu,MF_POPUP,reinterpret_cast<UINT_PTR>(sizes),L"图标大小");AppendMenuW(menu,MF_STRING,4,L"打开文件夹");AppendMenuW(menu,MF_SEPARATOR,0,nullptr);AppendMenuW(menu,MF_STRING,5,L"解散收纳框…");SetForegroundWindow(f->window);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,f->window,nullptr);DestroyMenu(menu);PostMessageW(f->window,WM_NULL,0,0);MenuCommand(f,cmd);}
void MenuCommand(Frame* f,int cmd){if(cmd==1){RenameFrame(f);}else if(cmd==2)Expand(f,!f->large);else if(cmd==3){f->box.locked=!f->box.locked;Persist();}else if(cmd==4)ShellExecuteW(f->window,L"open",f->box.path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);else if(cmd==5)Dissolve(f);else if(cmd>=20&&cmd<=22){f->box.size=static_cast<unsigned>(32+(cmd-20)*16);Persist();Paint(f);}}
LRESULT CALLBACK FrameProc(HWND w,UINT msg,WPARAM wp,LPARAM lp){auto f=reinterpret_cast<Frame*>(GetWindowLongPtrW(w,GWLP_USERDATA));if(msg==WM_NCCREATE){f=static_cast<Frame*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);f->window=w;SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(f));}if(!f)return DefWindowProcW(w,msg,wp,lp);
 if(f->menu3&&(msg==WM_INITMENUPOPUP||msg==WM_DRAWITEM||msg==WM_MEASUREITEM||msg==WM_MENUCHAR)){LRESULT result=0;if(SUCCEEDED(f->menu3->HandleMenuMsg2(msg,wp,lp,&result)))return result;}else if(f->menu2&&(msg==WM_INITMENUPOPUP||msg==WM_DRAWITEM||msg==WM_MEASUREITEM)){f->menu2->HandleMenuMsg(msg,wp,lp);return 0;}
 switch(msg){case WM_APP+8:Paint(f);return 0;case WM_CREATE:{auto target=new DropTarget(f);RegisterDragDrop(w,target);target->Release();return 0;}
 case WM_MOUSEACTIVATE:if(!f->large)return MA_NOACTIVATE;break;
 case WM_ERASEBKGND:return 1;
 case WM_PAINT:{PAINTSTRUCT ps{};BeginPaint(w,&ps);EndPaint(w,&ps);Paint(f);return 0;}
 case WM_NCHITTEST:{POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};ScreenToClient(w,&p);RECT r{};GetClientRect(w,&r);auto button=f->Button();if(PtInRect(&button,p))return HTCLIENT;if(!f->large&&!f->animating&&!f->box.locked){int edge=f->D(9);bool left=p.x<edge,right=p.x>r.right-edge,top=p.y<f->D(20),bottom=p.y>r.bottom-edge;if(top&&left)return HTTOPLEFT;if(top&&right)return HTTOPRIGHT;if(bottom&&left)return HTBOTTOMLEFT;if(bottom&&right)return HTBOTTOMRIGHT;if(left)return HTLEFT;if(right)return HTRIGHT;if(bottom)return HTBOTTOM;if(top&&p.y>f->D(8)&&p.x<r.right/3)return HTTOP;if(p.y<f->D(40))return HTCAPTION;}return HTCLIENT;}
 case WM_NCCALCSIZE:return 0;
 case WM_GETMINMAXINFO:{auto info=reinterpret_cast<MINMAXINFO*>(lp);info->ptMinTrackSize={f->D(220),f->D(160)};return 0;}
 case WM_ENTERSIZEMOVE:++interaction;return 0;
 case WM_EXITSIZEMOVE:{if(interaction)--interaction;if(!f->large){RECT r{};GetWindowRect(w,&r);f->box.x=r.left;f->box.y=r.top;f->box.w=r.right-r.left;f->box.h=r.bottom-r.top;Persist();}return 0;}
 case WM_SIZE:if(!f->animating)Paint(f);return 0;
 case WM_DPICHANGED:if(!f->large){auto r=reinterpret_cast<RECT*>(lp);SetWindowPos(w,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOACTIVATE|SWP_NOZORDER);}Paint(f);return 0;
 case WM_MOUSEMOVE:{POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};auto b=f->Button();bool button=PtInRect(&b,p)!=FALSE;if(button!=f->buttonHover){f->buttonHover=button;Paint(f);}if(!f->hover){f->hover=true;TRACKMOUSEEVENT track{sizeof(track),TME_LEAVE,w,0};TrackMouseEvent(&track);Paint(f);}if(f->pressed&&(abs(p.x-f->press.x)>GetSystemMetrics(SM_CXDRAG)||abs(p.y-f->press.y)>GetSystemMetrics(SM_CYDRAG))){f->pressed=false;ReleaseCapture();DragOut(f);}return 0;}
 case WM_MOUSELEAVE:f->hover=false;Paint(f);return 0;
 case WM_LBUTTONDOWN:{SetFocus(w);POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};auto button=f->Button();if(PtInRect(&button,p)){Expand(f,!f->large);return 0;}int index=f->Hit(p);if(index>=0){if(!(GetKeyState(VK_CONTROL)&0x8000)&&!f->selected.count(index))f->selected.clear();if((GetKeyState(VK_CONTROL)&0x8000)&&f->selected.count(index))f->selected.erase(index);else f->selected.insert(index);f->press=p;f->pressed=true;SetCapture(w);}else f->selected.clear();Paint(f);return 0;}
 case WM_LBUTTONUP:f->pressed=false;if(GetCapture()==w)ReleaseCapture();return 0;
 case WM_CAPTURECHANGED:f->pressed=false;return 0;
 case WM_LBUTTONDBLCLK:{int index=f->Hit({GET_X_LPARAM(lp),GET_Y_LPARAM(lp)});if(index>=0)ShellExecuteW(w,L"open",f->content->items[static_cast<size_t>(index)].path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);return 0;}
 case WM_MOUSEWHEEL:{if(f->animating)return 0;f->wheel+=GET_WHEEL_DELTA_WPARAM(wp);int steps=f->wheel/WHEEL_DELTA;f->wheel%=WHEEL_DELTA;f->scroll=std::clamp(f->scroll-steps,0,f->Grid().MaxScroll(static_cast<int>(f->content->items.size())));Paint(f);return 0;}
 case WM_KEYDOWN:{if(wp==VK_ESCAPE){if(f->large)Expand(f,false);else{f->selected.clear();Paint(f);}}else if(wp==VK_F2){RenameFrame(f);}else if(wp==VK_RETURN){auto paths=Selected(f);if(!paths.empty())ShellExecuteW(w,L"open",paths[0].c_str(),nullptr,nullptr,SW_SHOWNORMAL);else Expand(f,!f->large);}else if(wp=='A'&&(GetKeyState(VK_CONTROL)&0x8000)){for(int i=0;i<static_cast<int>(f->content->items.size());++i)f->selected.insert(i);Paint(f);}else if(wp==VK_LEFT||wp==VK_RIGHT||wp==VK_UP||wp==VK_DOWN){int i=f->selected.empty()?0:*f->selected.begin();i+=wp==VK_LEFT?-1:wp==VK_RIGHT?1:wp==VK_UP?-f->Grid().columns:f->Grid().columns;if(!f->content->items.empty()){i=std::clamp(i,0,static_cast<int>(f->content->items.size())-1);f->selected={i};auto grid=f->Grid();int row=i/grid.columns;if(row<f->scroll)f->scroll=row;if(row>=f->scroll+grid.rows)f->scroll=row-grid.rows+1;Paint(f);}}return 0;}
 case WM_ACTIVATE:if(LOWORD(wp)==WA_INACTIVE&&f->large&&!interaction)SetTimer(w,3,80,nullptr);return 0;
 case WM_NCRBUTTONUP:SendMessageW(w,WM_CONTEXTMENU,reinterpret_cast<WPARAM>(w),lp);return 0;
 case WM_RBUTTONUP:{POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};ClientToScreen(w,&p);SendMessageW(w,WM_CONTEXTMENU,reinterpret_cast<WPARAM>(w),MAKELPARAM(p.x,p.y));return 0;}
 case WM_CONTEXTMENU:{POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(p.x==-1){GetCursorPos(&p);if(!f->selected.empty()){FileMenu(f,p);return 0;}}POINT local=p;ScreenToClient(w,&local);int index=f->Hit(local);if(index>=0){if(!f->selected.count(index))f->selected={index};Paint(f);FileMenu(f,p);}else Menu(f,p);return 0;}
 case Refresh:SetTimer(w,1,180,nullptr);return 0;
 case WM_TIMER:if(wp==6){AnimationStep(f);return 0;}KillTimer(w,wp);if(wp==1)f->Scan();else if(wp==3&&f->large&&!interaction&&GetForegroundWindow()!=w&&GetForegroundWindow()!=shade)Expand(f,false);return 0;
 case Loaded:{std::unique_ptr<Batch> batch(reinterpret_cast<Batch*>(lp));if(f->loader.joinable())f->loader.join();f->busy=false;auto rank=[&](const Item& i){auto it=std::find(f->box.order.begin(),f->box.order.end(),i.name);return static_cast<size_t>(it-f->box.order.begin());};std::stable_sort(batch->items.begin(),batch->items.end(),[&](const Item&a,const Item&b){return rank(a)<rank(b);});auto selected=Selected(f);f->selected.clear();f->content=std::move(batch);for(size_t i=0;i<f->content->items.size();++i)if(std::find(selected.begin(),selected.end(),f->content->items[i].path)!=selected.end())f->selected.insert(static_cast<int>(i));Paint(f);if(f->again){f->again=false;f->Scan();}return 0;}
 case WM_CLOSE:if(f->large)Expand(f,false);return 0;
 case WM_DESTROY:RevokeDragDrop(w);return 0;
 }return DefWindowProcW(w,msg,wp,lp);}
BOOL CALLBACK FindDesktop(HWND w,LPARAM p){if(FindWindowExW(w,nullptr,L"SHELLDLL_DefView",nullptr)){*reinterpret_cast<HWND*>(p)=w;return FALSE;}return TRUE;}
void Rebuild(){if(interaction){SetTimer(controller,1,250,nullptr);return;}rebuilding=true;HideShade();expanded=nullptr;frames.clear();desktop=nullptr;EnumWindows(FindDesktop,reinterpret_cast<LPARAM>(&desktop));if(!desktop)desktop=FindWindowW(L"Progman",nullptr);if(!desktop){rebuilding=false;SetTimer(controller,1,1500,nullptr);return;}
 for(auto& box:desk::Load()){auto f=std::make_unique<Frame>();f->box=box;f->box.collapsed=false;RECT r{box.x,box.y,box.x+box.w,box.y+box.h};MONITORINFO monitor{sizeof(monitor)};GetMonitorInfoW(MonitorFromRect(&r,MONITOR_DEFAULTTONEAREST),&monitor);f->box.x=std::clamp<LONG>(box.x,monitor.rcWork.left,(std::max)(monitor.rcWork.left,monitor.rcWork.right-box.w));f->box.y=std::clamp<LONG>(box.y,monitor.rcWork.top,(std::max)(monitor.rcWork.top,monitor.rcWork.bottom-box.h));POINT p{f->box.x,f->box.y};
  CreateWindowExW(WS_EX_TOOLWINDOW|WS_EX_LAYERED,FrameClass,box.name.c_str(),WS_POPUP|WS_VISIBLE|WS_THICKFRAME,p.x,p.y,box.w,box.h,desktop,nullptr,GetModuleHandleW(nullptr),f.get());if(f->window){SetWindowPos(f->window,HWND_BOTTOM,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE|SWP_SHOWWINDOW|SWP_FRAMECHANGED);Paint(f.get());PostMessageW(f->window,WM_APP+8,0,0);f->Scan();f->Watch();frames.push_back(std::move(f));}}
 try{std::ofstream log(desk::DataDir()/L"desktop-state.txt");log<<"frames="<<frames.size()<<"\n";for(auto& frame:frames)log<<"visible="<<IsWindowVisible(frame->window)<<" painted="<<frame->painted<<" child="<<((GetWindowLongPtrW(frame->window,GWL_STYLE)&WS_CHILD)!=0)<<"\n";}catch(...){}
 rebuilding=false;}
void NewBox(){try{auto boxes=desk::Load();if(boxes.size()>=64)return;desk::Box box;box.name=L"新建收纳框";POINT cursor{};GetCursorPos(&cursor);box.x=cursor.x;box.y=cursor.y;box.w=380;box.h=290;GUID id{};CoCreateGuid(&id);wchar_t text[40]{};StringFromGUID2(id,text,40);box.id=text;
 auto root=desk::CollectionsDir();std::filesystem::create_directories(root);auto path=root/box.name;for(int n=2;std::filesystem::exists(path)||std::any_of(boxes.begin(),boxes.end(),[&](const desk::Box& existing){return _wcsicmp(existing.name.c_str(),path.filename().c_str())==0;});++n)path=root/(box.name+L" "+std::to_wstring(n));std::filesystem::create_directory(path);box.path=path.wstring();box.name=path.filename().wstring();boxes.push_back(box);if(!desk::Save(boxes)){MessageBoxW(controller,L"创建失败：无法保存收纳布局。文件夹已保留。",L"TidyDesk",MB_OK|MB_ICONERROR);return;}
 HKEY key=nullptr;if(RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\TidyDesk",0,nullptr,0,KEY_SET_VALUE,nullptr,&key,nullptr)==ERROR_SUCCESS){DWORD enabled=1;RegSetValueExW(key,L"Desktop",0,REG_DWORD,reinterpret_cast<BYTE*>(&enabled),sizeof(enabled));RegCloseKey(key);}Rebuild();if(std::none_of(frames.begin(),frames.end(),[&](const auto& f){return f->box.id==box.id&&IsWindowVisible(f->window)&&f->painted;})){MessageBoxW(controller,L"文件夹已创建，但桌面窗口未能显示。请在设置中刷新收纳列表后重试。",L"TidyDesk",MB_OK|MB_ICONERROR);}
 }catch(...){MessageBoxW(controller,L"无法创建收纳文件夹，请检查文档目录的权限。",L"TidyDesk",MB_OK|MB_ICONWARNING);}}
LRESULT CALLBACK Controller(HWND w,UINT m,WPARAM wp,LPARAM lp){if(m==shellMessage&&shellMessage){SetTimer(w,1,1500,nullptr);return 0;}switch(m){case WM_APP+1:Rebuild();return 0;case WM_APP+4:return wp<frames.size()?static_cast<LRESULT>(frames[wp]->content->items.size()+1):0;case WM_APP+6:if(wp<frames.size())Expand(frames[wp].get(),true);return 0;case NewCollection:NewBox();return 0;case WM_DISPLAYCHANGE:case WM_DPICHANGED:SetTimer(w,1,400,nullptr);return 0;case WM_TIMER:if(wp==2){if(!interaction){KillTimer(w,2);DestroyWindow(w);}return 0;}KillTimer(w,1);Rebuild();return 0;case WM_CLOSE:if(interaction){SetTimer(w,2,250,nullptr);return 0;}DestroyWindow(w);return 0;case WM_DESTROY:rebuilding=true;HideShade();expanded=nullptr;frames.clear();PostQuitMessage(0);return 0;}return DefWindowProcW(w,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR command,int){
 int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(argv&&argc==4&&wcscmp(argv[1],L"--icon-preview")==0){int result=desk::ExportCollectionIcon(argv[2],argv[3]);LocalFree(argv);return result;}if(argv)LocalFree(argv);
 if(wcscmp(command,L"--test-rename")==0)return desk::RenameTest();if(wcscmp(command,L"--test-shortcut-icon")==0)return desk::ShortcutIconTest();if(wcscmp(command,L"--test-icon-pixels")==0)return desk::IconPixelsTest();if(wcscmp(command,L"--test-model")==0)return desk::ModelTest();if(wcscmp(command,L"--test-transfer")==0)return desk::TransferTest();if(wcscmp(command,L"--test-geometry")==0)return desk::GeometryTest();bool testFrame=wcscmp(command,L"--test-frame")==0;bool create=wcscmp(command,L"--new")==0;if(*command&&!create&&!testFrame)return 2;
 HANDLE single=CreateMutexW(nullptr,FALSE,testFrame?L"Local\\TidyDesk.Desktop.FrameTest":L"Local\\TidyDesk.Desktop.Singleton");if(!single)return 3;if(GetLastError()==ERROR_ALREADY_EXISTS){if(create){HWND existing=nullptr;for(int retry=0;retry<60&&!existing;++retry){existing=FindWindowW(L"TidyDesk.Desktop.Controller",nullptr);if(!existing)Sleep(50);}if(!existing||!PostMessageW(existing,NewCollection,0,0))MessageBoxW(nullptr,L"收纳模块尚未就绪，请稍后重试。",L"TidyDesk",MB_OK|MB_ICONERROR);}CloseHandle(single);return 0;}
 if(FAILED(OleInitialize(nullptr))){CloseHandle(single);return 4;}ULONG_PTR token=0;GdiplusStartupInput input;if(GdiplusStartup(&token,&input,nullptr)!=Ok){OleUninitialize();CloseHandle(single);return 5;}INITCOMMONCONTROLSEX controls{sizeof(controls),ICC_STANDARD_CLASSES};InitCommonControlsEx(&controls);
 WNDCLASSW wc{};wc.hInstance=instance;wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.style=CS_DBLCLKS;wc.lpfnWndProc=FrameProc;wc.lpszClassName=FrameClass;RegisterClassW(&wc);wc.lpfnWndProc=ShadeProc;wc.lpszClassName=L"TidyDesk.Desktop.Shade";RegisterClassW(&wc);wc.lpfnWndProc=NameProc;wc.lpszClassName=L"TidyDesk.Desktop.Name";wc.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);RegisterClassW(&wc);wc.lpfnWndProc=Controller;wc.lpszClassName=L"TidyDesk.Desktop.Controller";RegisterClassW(&wc);
 if(testFrame){int result=0;HWND parent=CreateWindowExW(WS_EX_TOOLWINDOW,wc.lpszClassName,L"Test owner",WS_POPUP,0,0,800,600,nullptr,nullptr,instance,nullptr);{Frame f;f.testAnimation=true;f.box.name=L"默认收纳格";f.box.x=40;f.box.y=40;f.box.w=380;f.box.h=290;for(int i=0;i<100;++i){Item item;item.name=item.label=L"项目 "+std::to_wstring(i);f.content->items.push_back(std::move(item));}CreateWindowExW(WS_EX_TOOLWINDOW|WS_EX_LAYERED,FrameClass,f.box.name.c_str(),WS_POPUP|WS_VISIBLE|WS_THICKFRAME,40,40,380,290,parent,nullptr,instance,&f);if(f.window){Paint(&f);if(!IsWindowVisible(f.window)||!f.painted||!f.hitSurface||(GetWindowLongPtrW(f.window,GWL_STYLE)&WS_CHILD))result=21;Expand(&f,true,false);RECT actual{};MONITORINFO monitor{sizeof(monitor)};GetMonitorInfoW(MonitorFromWindow(f.window,MONITOR_DEFAULTTONEAREST),&monitor);if(!shade||!GetWindowRect(shade,&actual)||!EqualRect(&actual,&monitor.rcMonitor)||!(GetWindowLongPtrW(shade,GWL_EXSTYLE)&WS_EX_TOPMOST))result=22;Expand(&f,false,false);if(GetWindowLongPtrW(f.window,GWL_EXSTYLE)&WS_EX_TOPMOST)result=23;RECT initial{};GetWindowRect(f.window,&initial);Expand(&f,true);if(!f.animating)result=30;if(f.animating){RECT first{};GetWindowRect(f.window,&first);if(!EqualRect(&initial,&first)||!f.contentFrom||!f.contentTo)result=25;auto source=f.contentFrom.get(),target=f.contentTo.get();auto dc=f.surface.dc;f.animationStart-=90;AnimationStep(&f);RECT middle{};GetWindowRect(f.window,&middle);if(EqualRect(&middle,&initial)||f.contentFrom.get()!=source||f.contentTo.get()!=target||f.surface.dc!=dc)result=26;Expand(&f,false);RECT reversed{};GetWindowRect(f.window,&reversed);if(!EqualRect(&middle,&reversed)||!shade)result=27;Expand(&f,true);GetWindowRect(f.window,&reversed);if(!EqualRect(&middle,&reversed))result=28;}auto deadline=GetTickCount64()+1000;while(f.animating&&GetTickCount64()<deadline){MSG event{};while(PeekMessageW(&event,nullptr,0,0,PM_REMOVE)){TranslateMessage(&event);DispatchMessageW(&event);}Sleep(5);}if(f.animating||interaction||f.contentFrom||f.contentTo||f.surface.dc)result=24;Expand(&f,false);deadline=GetTickCount64()+1000;while(f.animating&&GetTickCount64()<deadline){MSG event{};while(PeekMessageW(&event,nullptr,0,0,PM_REMOVE)){TranslateMessage(&event);DispatchMessageW(&event);}Sleep(5);}RECT end{};GetWindowRect(f.window,&end);if(f.animating||interaction||shade||!EqualRect(&end,&initial)||f.contentFrom||f.contentTo||f.surface.dc)result=29;Expand(&f,false,false);}else result=20;}DestroyWindow(parent);GdiplusShutdown(token);OleUninitialize();CloseHandle(single);return result;}
 controller=CreateWindowExW(WS_EX_TOOLWINDOW,wc.lpszClassName,L"TidyDesk desktop",WS_POPUP,0,0,0,0,nullptr,nullptr,instance,nullptr);shellMessage=RegisterWindowMessageW(L"TaskbarCreated");Rebuild();if(create)PostMessageW(controller,NewCollection,0,0);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}GdiplusShutdown(token);OleUninitialize();CloseHandle(single);return 0;
}
