// SPDX-License-Identifier: MIT
#include "settings.h"
#include "desktop_model.h"
#include <commctrl.h>
#include <dwmapi.h>
#include <uxtheme.h>
#include <shellapi.h>
#include <shlobj.h>
#include <string>
#include <vector>
#include <algorithm>
#include <set>
#include <gdiplus.h>
namespace {
const wchar_t* Key=L"Software\\TidyDesk";constexpr wchar_t OldKey[]=L"Software\\LiteTaskbar",Run[]=L"Software\\Microsoft\\Windows\\CurrentVersion\\Run";
HWND page=nullptr,ownerWindow=nullptr;HFONT font=nullptr,titleFont=nullptr;HBRUSH bg=nullptr;
Preferences draft;int active=0,selected=-1;bool building=false,dark=false;std::wstring backendStatus=L"尚未应用";std::vector<desk::Box> boxes;
struct Position{HWND w;int x,y,width,height;bool stretch;};std::vector<Position> positions;
COLORREF Background(){return dark?RGB(32,32,32):RGB(249,249,249);}COLORREF Text(){return dark?RGB(245,245,245):RGB(26,26,26);}
int Scale(int n){return MulDiv(n,static_cast<int>(GetDpiForWindow(page)),96);}
DWORD Get(const wchar_t* name,DWORD fallback){DWORD v=0,b=sizeof(v);return RegGetValueW(HKEY_CURRENT_USER,Key,name,RRF_RT_REG_DWORD,nullptr,&v,&b)==ERROR_SUCCESS?v:fallback;}
LSTATUS Put(const wchar_t* name,DWORD value){HKEY k=nullptr;auto e=RegCreateKeyExW(HKEY_CURRENT_USER,Key,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,nullptr);if(!e){e=RegSetValueExW(k,name,0,REG_DWORD,reinterpret_cast<BYTE*>(&value),sizeof(value));RegCloseKey(k);}return e;}
bool OwnedOld(const std::wstring& value){auto pos=value.find(L'"',1);if(value.empty()||value.front()!=L'"'||pos==std::wstring::npos)return false;auto p=std::filesystem::path(value.substr(1,pos-1));return _wcsicmp(p.filename().c_str(),L"LiteTaskbar.exe")==0;}
std::wstring RunValue(const wchar_t* name){wchar_t b[32768]{};DWORD size=sizeof(b);if(RegGetValueW(HKEY_CURRENT_USER,Run,name,RRF_RT_REG_SZ,nullptr,b,&size)!=ERROR_SUCCESS)return {};return b;}
bool StartupEnabled(){return !RunValue(L"TidyDesk").empty();}
LSTATUS Startup(bool enabled){HKEY k=nullptr;auto e=RegCreateKeyExW(HKEY_CURRENT_USER,Run,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,nullptr);if(e)return e;
 if(enabled){wchar_t path[32768]{};auto n=GetModuleFileNameW(nullptr,path,32768);if(!n||n>=32768){RegCloseKey(k);return ERROR_BAD_PATHNAME;}std::wstring cmd=L"\""+std::wstring(path)+L"\" --background";if(cmd.size()>=260){RegCloseKey(k);return ERROR_FILENAME_EXCED_RANGE;}e=RegSetValueExW(k,L"TidyDesk",0,REG_SZ,reinterpret_cast<const BYTE*>(cmd.c_str()),static_cast<DWORD>((cmd.size()+1)*2));}
 else{e=RegDeleteValueW(k,L"TidyDesk");if(e==ERROR_FILE_NOT_FOUND)e=ERROR_SUCCESS;}
 if(!e&&OwnedOld(RunValue(L"LiteTaskbar")))RegDeleteValueW(k,L"LiteTaskbar");RegCloseKey(k);return e;}
void Theme(){DWORD light=1,b=sizeof(light);RegGetValueW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",L"AppsUseLightTheme",RRF_RT_REG_DWORD,nullptr,&light,&b);auto appliedTheme=Get(L"Theme",0);dark=appliedTheme==2||(appliedTheme==0&&!light);if(bg)DeleteObject(bg);bg=CreateSolidBrush(Background());BOOL enabled=dark;DwmSetWindowAttribute(page,20,&enabled,sizeof(enabled));}
bool startupDraft=false,startupSaved=false,hideDraft=false,hideSaved=false,arrowKnown=true,dirty=false,applying=false;HANDLE arrowProcess=nullptr;Preferences appliedDraft;bool awaitingTaskbar=false;std::set<std::wstring> editedBoxes;
std::wstring feedback;std::vector<RECT> cards;
bool ArrowHidden(){wchar_t current[32768]{},owned[32768]{};DWORD bytes=sizeof(current);auto e=RegGetValueW(HKEY_LOCAL_MACHINE,L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Icons",L"29",RRF_RT_REG_SZ|RRF_SUBKEY_WOW6464KEY,nullptr,current,&bytes);arrowKnown=e==ERROR_SUCCESS||e==ERROR_FILE_NOT_FOUND;if(e)return false;bytes=sizeof(owned);if(RegGetValueW(HKEY_LOCAL_MACHINE,L"SOFTWARE\\TidyDesk\\ArrowBackup",L"Owned",RRF_RT_REG_SZ|RRF_SUBKEY_WOW6464KEY,nullptr,owned,&bytes))return false;return _wcsicmp(current,owned)==0;}
LRESULT CALLBACK ThemeCombo(HWND w,UINT msg,WPARAM wp,LPARAM lp,UINT_PTR,DWORD_PTR){
 auto result=DefSubclassProc(w,msg,wp,lp);
 if(msg==WM_PAINT||msg==WM_PRINTCLIENT||msg==WM_PRINT){HDC dc=msg==WM_PAINT?GetDC(w):reinterpret_cast<HDC>(wp);if(!dc)return result;RECT r{};GetClientRect(w,&r);SetDCBrushColor(dc,dark?RGB(48,48,48):RGB(255,255,255));FillRect(dc,&r,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));auto brush=CreateSolidBrush(dark?RGB(100,100,100):RGB(155,155,155));FrameRect(dc,&r,brush);DeleteObject(brush);auto old=SelectObject(dc,font);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,Text());wchar_t text[80]{};auto selectedItem=SendMessageW(w,CB_GETCURSEL,0,0);if(selectedItem!=CB_ERR)SendMessageW(w,CB_GETLBTEXT,static_cast<WPARAM>(selectedItem),reinterpret_cast<LPARAM>(text));RECT label=r;label.left+=Scale(10);label.right-=Scale(30);DrawTextW(dc,text,-1,&label,DT_SINGLELINE|DT_LEFT|DT_VCENTER);SelectObject(dc,old);auto pen=CreatePen(PS_SOLID,Scale(1),Text());old=SelectObject(dc,pen);int x=r.right-Scale(16),y=r.bottom/2;MoveToEx(dc,x-Scale(4),y-Scale(2),nullptr);LineTo(dc,x,y+Scale(2));LineTo(dc,x+Scale(4),y-Scale(2));SelectObject(dc,old);DeleteObject(pen);if(GetFocus()==w){InflateRect(&r,-Scale(3),-Scale(3));DrawFocusRect(dc,&r);}if(msg==WM_PAINT)ReleaseDC(w,dc);}
 return result;
}
HWND Control(const wchar_t* cls,const wchar_t* text,DWORD style,int id,int x,int y,int width,int height,bool stretch=false){auto w=CreateWindowExW(0,cls,text,WS_CHILD|WS_VISIBLE|style,Scale(x),Scale(y),Scale(width),Scale(height),page,reinterpret_cast<HMENU>(static_cast<INT_PTR>(id)),GetModuleHandleW(nullptr),nullptr);SendMessageW(w,WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);SetWindowTheme(w,dark?L"DarkMode_Explorer":L"Explorer",nullptr);positions.push_back({w,x,y,width,height,stretch});return w;}
HWND Button(const wchar_t* text,int id,int x,int y,int width=132){return Control(L"BUTTON",text,BS_OWNERDRAW|WS_TABSTOP,id,x,y,width,34);}
void Label(const wchar_t* text,int x,int y,int width=580,int height=24,int id=0){Control(L"STATIC",text,0,id,x,y,width,height,true);}
void Card(int y,int height){cards.push_back({244,y,928,y+height});}
void Toggle(const wchar_t* label,int id,int y,bool checked){auto w=Control(L"BUTTON",label,BS_AUTOCHECKBOX|WS_TABSTOP,id,264,y,640,36,true);SendMessageW(w,BM_SETCHECK,checked?BST_CHECKED:BST_UNCHECKED,0);}
void Status(const wchar_t* text){feedback=text;if(page)SetDlgItemTextW(page,90,text);}
void Dirty(){dirty=true;Status(L"有未应用的更改");EnableWindow(GetDlgItem(page,300),TRUE);EnableWindow(GetDlgItem(page,301),TRUE);}
void Layout(){RECT r{};GetClientRect(page,&r);int width=MulDiv(r.right,96,static_cast<int>(GetDpiForWindow(page))),height=MulDiv(r.bottom,96,static_cast<int>(GetDpiForWindow(page)));int extra=width-960;for(auto& p:positions){int id=GetDlgCtrlID(p.w);if(id==300||id==301)MoveWindow(p.w,Scale(width-(id==300?148:280)),Scale(height-54),Scale(116),Scale(34),TRUE);else if(id==240)MoveWindow(p.w,Scale(width-276),Scale(p.y),Scale(p.width),Scale(p.height),TRUE);else if(id==90)MoveWindow(p.w,Scale(244),Scale(height-53),Scale((std::max)(120,width-544)),Scale(38),TRUE);else MoveWindow(p.w,Scale(p.x),Scale(p.y),Scale((std::max)(40,p.width+(p.stretch?extra:0))),Scale(p.height),TRUE);}InvalidateRect(page,nullptr,TRUE);}
void Build(){building=true;for(auto& p:positions)DestroyWindow(p.w);positions.clear();cards.clear();if(font)DeleteObject(font);if(titleFont)DeleteObject(titleFont);Theme();font=CreateFontW(-Scale(14),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Microsoft YaHei UI");titleFont=CreateFontW(-Scale(28),0,0,0,FW_SEMIBOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Microsoft YaHei UI");
 const wchar_t* names[]={L"任务栏",L"桌面收纳",L"图标",L"常规"};for(int i=0;i<4;++i)Button(names[i],100+i,12,32+i*48,196);
 auto title=Control(L"STATIC",names[active],0,0,244,28,640,44,true);SendMessageW(title,WM_SETFONT,reinterpret_cast<WPARAM>(titleFont),TRUE);
 if(active==0){Card(96,132);Label(L"任务栏背景",264,110);auto text=L"不透明度  "+std::to_wstring(draft.opacity)+L"%";Label(text.c_str(),264,146,580,24,61);auto slider=Control(TRACKBAR_CLASSW,L"任务栏背景不透明度",TBS_NOTICKS|WS_TABSTOP,12,262,176,636,32,true);SendMessageW(slider,TBM_SETRANGE,TRUE,MAKELPARAM(0,100));SendMessageW(slider,TBM_SETPOS,TRUE,draft.opacity);
 Card(240,96);Toggle(L"存在最大化窗口时使用系统背景",13,252,draft.maximized);Label(L"包括被普通窗口遮住的最大化窗口。",264,296,580,24);
 }
 if(active==1){Card(96,76);Toggle(L"启用桌面收纳",200,115,draft.desktop);Label(L"已有收纳框",244,196);Button(L"刷新列表",215,772,186,132);if(!boxes.empty()){auto list=Control(L"LISTBOX",L"已有收纳框",LBS_NOTIFY|WS_BORDER|WS_VSCROLL|WS_TABSTOP,201,244,234,260,240);for(auto& box:boxes)SendMessageW(list,LB_ADDSTRING,0,reinterpret_cast<LPARAM>(box.name.c_str()));
 selected=std::clamp(selected,0,static_cast<int>(boxes.size())-1);SendMessageW(list,LB_SETCURSEL,selected,0);auto& box=boxes[static_cast<size_t>(selected)];Label(L"名称",528,235,376);Control(L"EDIT",box.name.c_str(),WS_BORDER|WS_TABSTOP|ES_AUTOHSCROLL,202,528,266,376,32,true);Label(box.path.c_str(),528,316,376,70);Button(L"打开文件夹",212,528,406,176);Button(L"在桌面展开",213,716,406,188);Toggle(L"锁定所选收纳框位置",214,496,box.locked);Button(L"解散收纳框…",216,528,546,176);}
 else Label(L"暂无收纳框",244,250,640);
 }
 if(active==2){Card(96,92);Toggle(L"隐藏快捷方式箭头",230,108,hideDraft);Label(L"仅在点击“应用”时修改系统设置。",264,152);Card(204,154);Label(L"已保存的设置",264,220);Label(!arrowKnown?L"无法读取系统设置":hideSaved?L"隐藏箭头":L"显示箭头",264,255,620,44,93);Label(L"若图标尚未更新，可先刷新；仍未变化时注销后重新登录。",264,304,620,44);Button(L"修复并刷新图标",232,244,382,180);EnableWindow(GetDlgItem(page,230),arrowKnown);}
 if(active==3){Card(96,76);Toggle(L"登录 Windows 时启动",14,115,startupDraft);Card(184,86);Label(L"界面主题",264,209,280);auto combo=Control(L"COMBOBOX",L"界面主题",CBS_DROPDOWNLIST|CBS_OWNERDRAWFIXED|CBS_HASSTRINGS|WS_TABSTOP,240,684,207,220,160);for(auto text:{L"跟随系统",L"浅色",L"深色"})SendMessageW(combo,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(text));SetWindowSubclass(combo,ThemeCombo,1,0);SendMessageW(combo,CB_SETCURSEL,draft.theme,0);SendMessageW(combo,CB_SETITEMHEIGHT,static_cast<WPARAM>(-1),Scale(28));SendMessageW(combo,CB_SETITEMHEIGHT,0,Scale(30));Card(286,112);Label(L"数据位置",264,300);Button(L"配置文件夹",241,264,344,180);Button(L"收纳文件夹",242,456,344,180);Label(L"TidyDesk 0.4.4 实验版 · MIT · JamesGZM",244,436);Button(L"开源仓库",244,244,481,148);}
 Button(L"还原更改",301,680,620,116);Button(L"应用",300,812,620,116);Label(feedback.c_str(),244,622,400,38,90);EnableWindow(GetDlgItem(page,300),!applying&&(dirty||(active==0&&backendStatus.find(L"应用失败")==0)));EnableWindow(GetDlgItem(page,301),dirty&&!applying);Layout();building=false;
}
bool SaveCommon(){auto previous=appliedDraft;bool taskbarChanged=previous.opacity!=draft.opacity||previous.maximized!=draft.maximized;LSTATUS e=ERROR_SUCCESS;if(previous.opacity!=draft.opacity)e=Put(L"Opacity",draft.opacity);if(!e&&previous.maximized!=draft.maximized)e=Put(L"Maximized",draft.maximized);if(!e&&previous.theme!=draft.theme)e=Put(L"Theme",draft.theme);if(!e&&previous.desktop!=draft.desktop)e=Put(L"Desktop",draft.desktop);if(e){Status(L"配置保存失败；尚未应用全部更改。");return false;}
 if(startupDraft!=startupSaved){e=Startup(startupDraft);if(e){Status(L"登录启动设置失败；请重试应用。");return false;}startupSaved=startupDraft;}
 if(!boxes.empty()){auto latest=desk::Load();bool changedBoxes=false;for(auto& target:latest)for(const auto& edited:boxes)if(target.id==edited.id&&editedBoxes.count(edited.id)){if(target.name!=edited.name||target.locked!=edited.locked)changedBoxes=true;target.name=edited.name;target.locked=edited.locked;}if(changedBoxes&&!desk::Save(latest)){Status(L"收纳框设置保存失败；请重试。");return false;}if(changedBoxes)desk::Notify();}
 if(taskbarChanged)SendMessageW(ownerWindow,SettingsApply,draft.opacity,draft.maximized);if(previous.desktop!=draft.desktop){if(draft.desktop)desk::Start(page);else desk::Stop();}draft=LoadPreferences();appliedDraft=draft;startupDraft=startupSaved=StartupEnabled();editedBoxes.clear();dirty=false;awaitingTaskbar=taskbarChanged;Status(taskbarChanged?L"正在应用…":L"应用成功");Build();return true;}
void Apply(bool repairIcons=false){if(applying)return;if(!dirty&&!repairIcons){awaitingTaskbar=true;Status(L"正在应用…");SendMessageW(ownerWindow,SettingsRetry,0,0);return;}if(hideDraft!=hideSaved||repairIcons){wchar_t exe[32768]{};GetModuleFileNameW(nullptr,exe,32768);auto path=std::filesystem::path(exe).parent_path()/L"TidyDeskIcons.exe";SHELLEXECUTEINFOW info{sizeof(info)};info.fMask=SEE_MASK_NOCLOSEPROCESS;info.hwnd=page;info.lpVerb=L"runas";info.lpFile=path.c_str();info.lpParameters=hideDraft?L"--quiet-hide":L"--quiet-restore";info.nShow=SW_HIDE;if(!ShellExecuteExW(&info)||!info.hProcess){Status(L"图标设置已取消或未启动；更改尚未应用。");return;}arrowProcess=info.hProcess;applying=true;EnableWindow(page,FALSE);Status(L"正在应用系统图标设置…");SetTimer(page,2,100,nullptr);return;}SaveCommon();}
void ResetDraft(){draft=LoadPreferences();appliedDraft=draft;editedBoxes.clear();startupDraft=startupSaved=StartupEnabled();hideDraft=hideSaved=ArrowHidden();boxes=desk::Load();dirty=false;feedback.clear();Build();}
void DrawButton(const DRAWITEMSTRUCT* d){auto dc=d->hDC;RECT r=d->rcItem;bool nav=d->CtlID>=100&&d->CtlID<=103;bool selectedNav=nav&&static_cast<int>(d->CtlID)==100+active;bool enabled=!(d->itemState&ODS_DISABLED);auto base=nav?(dark?RGB(27,27,27):RGB(243,243,243)):Background();auto fill=nav&&!selectedNav?base:selectedNav?(dark?RGB(45,45,45):RGB(229,229,229)):d->CtlID==300&&enabled?RGB(0,112,120):(dark?RGB(52,52,52):RGB(255,255,255));SetDCBrushColor(dc,base);FillRect(dc,&r,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));auto brush=CreateSolidBrush(fill);auto pen=CreatePen(PS_SOLID,1,nav?fill:dark?RGB(68,68,68):RGB(211,211,211));auto ob=SelectObject(dc,brush),op=SelectObject(dc,pen);RoundRect(dc,r.left,r.top,r.right,r.bottom,Scale(6),Scale(6));SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(brush);DeleteObject(pen);
 if(selectedNav){RECT mark{r.left+Scale(2),r.top+Scale(8),r.left+Scale(5),r.bottom-Scale(8)};SetDCBrushColor(dc,RGB(0,142,149));FillRect(dc,&mark,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));}
 wchar_t label[180]{};GetWindowTextW(d->hwndItem,label,180);auto of=SelectObject(dc,font);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,!enabled?(dark?RGB(125,125,125):RGB(155,155,155)):d->CtlID==300?RGB(255,255,255):Text());if(nav){const wchar_t* glyphs[]={L"\xE7F4",L"\xE80A",L"\xE91B",L"\xE713"};auto symbols=CreateFontW(-Scale(18),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,ANTIALIASED_QUALITY,DEFAULT_PITCH,L"Segoe MDL2 Assets");auto before=SelectObject(dc,symbols);RECT icon=r;icon.left+=Scale(16);icon.right=icon.left+Scale(22);DrawTextW(dc,glyphs[d->CtlID-100],-1,&icon,DT_CENTER|DT_VCENTER|DT_SINGLELINE);SelectObject(dc,before);DeleteObject(symbols);r.left+=Scale(52);}DrawTextW(dc,label,-1,&r,(nav?DT_LEFT:DT_CENTER)|DT_VCENTER|DT_SINGLELINE);SelectObject(dc,of);if(d->itemState&ODS_FOCUS){InflateRect(&r,-3,-3);DrawFocusRect(dc,&r);}}
LRESULT CALLBACK Proc(HWND wnd,UINT msg,WPARAM wp,LPARAM lp){switch(msg){case WM_CREATE:page=wnd;Build();return 0;case WM_SIZE:Layout();return 0;
 case WM_MEASUREITEM:{auto item=reinterpret_cast<MEASUREITEMSTRUCT*>(lp);if(item->CtlID==240){item->itemHeight=static_cast<UINT>(Scale(30));return TRUE;}break;}
 case WM_GETMINMAXINFO:{auto i=reinterpret_cast<MINMAXINFO*>(lp);i->ptMinTrackSize={Scale(900),Scale(700)};return 0;}
 case WM_CTLCOLORSTATIC:case WM_CTLCOLORBTN:case WM_CTLCOLOREDIT:case WM_CTLCOLORLISTBOX:{auto dc=reinterpret_cast<HDC>(wp);SetTextColor(dc,Text());RECT r{};GetWindowRect(reinterpret_cast<HWND>(lp),&r);POINT point{r.left,r.top};ScreenToClient(wnd,&point);auto color=point.x<Scale(224)?(dark?RGB(27,27,27):RGB(243,243,243)):Background();for(auto card:cards)if(point.y>=Scale(card.top)&&point.y<Scale(card.bottom)&&point.x>=Scale(card.left))color=dark?RGB(43,43,43):RGB(251,251,251);SetBkColor(dc,color);SetDCBrushColor(dc,color);return reinterpret_cast<LRESULT>(GetStockObject(DC_BRUSH));}
 case WM_ERASEBKGND:{RECT r{};GetClientRect(wnd,&r);auto dc=reinterpret_cast<HDC>(wp);FillRect(dc,&r,bg);RECT side=r;side.right=Scale(224);SetDCBrushColor(dc,dark?RGB(27,27,27):RGB(243,243,243));FillRect(dc,&side,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));for(auto card:cards){auto brush=CreateSolidBrush(dark?RGB(43,43,43):RGB(251,251,251));auto pen=CreatePen(PS_SOLID,1,dark?RGB(51,51,51):RGB(231,231,231));auto ob=SelectObject(dc,brush),op=SelectObject(dc,pen);RoundRect(dc,Scale(card.left),Scale(card.top),r.right-Scale(32),Scale(card.bottom),Scale(8),Scale(8));SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(brush);DeleteObject(pen);}return 1;}
 case WM_NOTIFY:{auto n=reinterpret_cast<NMHDR*>(lp);int id=static_cast<int>(n->idFrom);if(n->code==NM_CUSTOMDRAW&&(id==13||id==14||id==200||id==230||id==214)){auto d=reinterpret_cast<NMCUSTOMDRAW*>(lp);if(d->dwDrawStage==CDDS_PREPAINT){auto dc=d->hdc;auto r=d->rc;bool on=SendMessageW(n->hwndFrom,BM_GETCHECK,0,0)==BST_CHECKED;SetDCBrushColor(dc,dark?RGB(43,43,43):RGB(251,251,251));FillRect(dc,&r,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));wchar_t text[180]{};GetWindowTextW(n->hwndFrom,text,180);auto old=SelectObject(dc,font);SetTextColor(dc,Text());SetBkMode(dc,TRANSPARENT);RECT label=r;label.right-=Scale(64);DrawTextW(dc,text,-1,&label,DT_LEFT|DT_VCENTER|DT_SINGLELINE);SelectObject(dc,old);int x=r.right-Scale(46),y=(r.bottom-Scale(20))/2;auto brush=CreateSolidBrush(on?RGB(0,130,138):dark?RGB(75,75,75):RGB(180,180,180));auto pen=CreatePen(PS_SOLID,1,on?RGB(0,130,138):dark?RGB(180,180,180):RGB(110,110,110));auto ob=SelectObject(dc,brush),op=SelectObject(dc,pen);RoundRect(dc,x,y,x+Scale(40),y+Scale(20),Scale(20),Scale(20));SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(brush);DeleteObject(pen);brush=CreateSolidBrush(RGB(255,255,255));ob=SelectObject(dc,brush);op=SelectObject(dc,GetStockObject(NULL_PEN));int cx=x+Scale(on?23:3);Ellipse(dc,cx,y+Scale(3),cx+Scale(14),y+Scale(17));SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(brush);if(GetFocus()==n->hwndFrom){InflateRect(&r,-2,-2);DrawFocusRect(dc,&r);}return CDRF_SKIPDEFAULT;}}break;}
 case WM_DRAWITEM:{auto d=reinterpret_cast<DRAWITEMSTRUCT*>(lp);if(d->CtlType==ODT_BUTTON){DrawButton(d);return TRUE;}if(d->CtlType==ODT_COMBOBOX&&d->CtlID==240){auto r=d->rcItem;SetDCBrushColor(d->hDC,(d->itemState&ODS_SELECTED)?(dark?RGB(55,70,72):RGB(220,240,240)):Background());FillRect(d->hDC,&r,static_cast<HBRUSH>(GetStockObject(DC_BRUSH)));wchar_t text[80]{};if(d->itemID!=static_cast<UINT>(-1))SendMessageW(d->hwndItem,CB_GETLBTEXT,d->itemID,reinterpret_cast<LPARAM>(text));auto old=SelectObject(d->hDC,font);SetBkMode(d->hDC,TRANSPARENT);SetTextColor(d->hDC,Text());r.left+=Scale(10);DrawTextW(d->hDC,text,-1,&r,DT_LEFT|DT_SINGLELINE|DT_VCENTER);SelectObject(d->hDC,old);if(d->itemState&ODS_FOCUS)DrawFocusRect(d->hDC,&r);return TRUE;}break;}
 case WM_HSCROLL:if(!building&&active==0&&reinterpret_cast<HWND>(lp)==GetDlgItem(wnd,12)){draft.opacity=static_cast<unsigned>(SendDlgItemMessageW(wnd,12,TBM_GETPOS,0,0));auto text=L"不透明度  "+std::to_wstring(draft.opacity)+L"%";SetDlgItemTextW(wnd,61,text.c_str());Dirty();}return 0;
 case WM_TIMER:if(wp==2&&arrowProcess&&WaitForSingleObject(arrowProcess,0)==WAIT_OBJECT_0){KillTimer(wnd,2);DWORD result=1;GetExitCodeProcess(arrowProcess,&result);CloseHandle(arrowProcess);arrowProcess=nullptr;applying=false;EnableWindow(wnd,TRUE);if(result==0){hideSaved=ArrowHidden();if(hideSaved==hideDraft){SHChangeNotify(SHCNE_ASSOCCHANGED,SHCNF_IDLIST,nullptr,nullptr);SaveCommon();}else Status(L"应用失败，请重试。");}else{wchar_t text[160]{};swprintf_s(text,L"图标设置未完成（%lu）；更改未应用，原备份保留。",result);Status(text);}}return 0;
 case WM_COMMAND:{if(building||applying)return 0;int id=LOWORD(wp),event=HIWORD(wp);if(id>=100&&id<=103){active=id-100;if(active==1&&editedBoxes.empty())boxes=desk::Load();Build();return 0;}if(id==300){Apply();return 0;}if(id==301){ResetDraft();return 0;}if(id==215){auto latest=desk::Load();for(auto& box:latest)for(const auto& edited:boxes)if(box.id==edited.id&&editedBoxes.count(box.id)){box.name=edited.name;box.locked=edited.locked;}boxes=std::move(latest);Build();return 0;}if(id==216&&selected>=0&&static_cast<size_t>(selected)<boxes.size()){auto idToRemove=boxes[static_cast<size_t>(selected)].id;if(desk::Dissolve(wnd,idToRemove)){editedBoxes.erase(idToRemove);boxes=desk::Load();Build();Status(L"收纳框已解散，文件已保留。");}return 0;}if(id==13){draft.maximized=IsDlgButtonChecked(wnd,13)==BST_CHECKED;Dirty();}else if(id==14){startupDraft=IsDlgButtonChecked(wnd,14)==BST_CHECKED;Dirty();}else if(id==200){draft.desktop=IsDlgButtonChecked(wnd,200)==BST_CHECKED;Dirty();}else if(id==230){hideDraft=IsDlgButtonChecked(wnd,230)==BST_CHECKED;Dirty();}else if(id==240&&event==CBN_SELCHANGE){draft.theme=static_cast<unsigned>(SendDlgItemMessageW(wnd,240,CB_GETCURSEL,0,0));Dirty();}
 else if(id==201&&event==LBN_SELCHANGE){selected=static_cast<int>(SendDlgItemMessageW(wnd,201,LB_GETCURSEL,0,0));Build();}else if(selected>=0&&static_cast<size_t>(selected)<boxes.size()){if(id==202&&event==EN_CHANGE){wchar_t text[128]{};GetDlgItemTextW(wnd,202,text,128);boxes[static_cast<size_t>(selected)].name=text;editedBoxes.insert(boxes[static_cast<size_t>(selected)].id);Dirty();}else if(id==214){boxes[static_cast<size_t>(selected)].locked=IsDlgButtonChecked(wnd,214)==BST_CHECKED;editedBoxes.insert(boxes[static_cast<size_t>(selected)].id);Dirty();}else if(id==212)ShellExecuteW(wnd,L"open",boxes[static_cast<size_t>(selected)].path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);else if(id==213){if(auto host=FindWindowW(L"TidyDesk.Desktop.Controller",nullptr))PostMessageW(host,WM_APP+6,static_cast<WPARAM>(selected),0);}}
 if(id==220){awaitingTaskbar=true;Status(L"正在应用…");SendMessageW(ownerWindow,SettingsRetry,0,0);}else if(id==232){if(dirty){Status(L"请先应用或还原更改，再修复图标。");return 0;}if(hideSaved){Apply(true);return 0;}SHChangeNotify(SHCNE_ASSOCCHANGED,SHCNF_IDLIST,nullptr,nullptr);Status(L"已请求系统刷新图标。");}else if(id==241||id==242){auto path=id==241?desk::DataDir():desk::CollectionsDir();std::error_code ec;std::filesystem::create_directories(path,ec);ShellExecuteW(wnd,L"open",path.c_str(),nullptr,nullptr,SW_SHOWNORMAL);}else if(id==244)ShellExecuteW(wnd,L"open",L"https://github.com/JamesGZM/TidyDesk",nullptr,nullptr,SW_SHOWNORMAL);return 0;}
 case WM_SETTINGCHANGE:if(draft.theme==0)Build();return 0;case WM_DPICHANGED:{auto r=reinterpret_cast<RECT*>(lp);SetWindowPos(wnd,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE);Build();return 0;}
 case WM_CLOSE:if(applying)return 0;if(dirty&&MessageBoxW(wnd,L"更改尚未应用。关闭并放弃这些更改？",L"TidyDesk",MB_OKCANCEL|MB_ICONQUESTION)!=IDOK)return 0;DestroyWindow(wnd);return 0;
 case WM_DESTROY:if(arrowProcess){CloseHandle(arrowProcess);arrowProcess=nullptr;}DeleteObject(font);DeleteObject(titleFont);DeleteObject(bg);font=nullptr;titleFont=nullptr;bg=nullptr;positions.clear();cards.clear();boxes.clear();page=nullptr;dirty=false;applying=false;return 0;}return DefWindowProcW(wnd,msg,wp,lp);}
}
Preferences LoadPreferences(){if(Get(L"Migrated",0)==0){HKEY old=nullptr,newKey=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,OldKey,0,KEY_READ,&old)==ERROR_SUCCESS){if(RegCreateKeyExW(HKEY_CURRENT_USER,Key,0,nullptr,0,KEY_WRITE,nullptr,&newKey,nullptr)==ERROR_SUCCESS){auto result=RegCopyTreeW(old,nullptr,newKey);RegCloseKey(newKey);if(result!=ERROR_SUCCESS){RegCloseKey(old);return {};}}RegCloseKey(old);}Put(L"Migrated",1);}Preferences p;p.opacity=(std::min)(100UL,Get(L"Opacity",0));p.maximized=Get(L"Maximized",0)!=0;p.desktop=Get(L"Desktop",0)!=0;p.theme=(std::min)(2UL,Get(L"Theme",0));return p;}
void ShowSettings(HWND owner,Preferences){if(page){ShowWindow(page,SW_RESTORE);SetForegroundWindow(page);return;}draft=LoadPreferences();appliedDraft=draft;editedBoxes.clear();startupDraft=startupSaved=StartupEnabled();hideDraft=hideSaved=ArrowHidden();dirty=false;feedback.clear();boxes=desk::Load();ownerWindow=owner;INITCOMMONCONTROLSEX controls{sizeof(controls),ICC_BAR_CLASSES};InitCommonControlsEx(&controls);WNDCLASSW wc{};wc.lpfnWndProc=Proc;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"TidyDesk.Settings";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&wc);UINT dpi=GetDpiForSystem();RECT r{0,0,MulDiv(960,static_cast<int>(dpi),96),MulDiv(680,static_cast<int>(dpi),96)};AdjustWindowRectExForDpi(&r,WS_OVERLAPPEDWINDOW,FALSE,WS_EX_APPWINDOW,dpi);page=CreateWindowExW(WS_EX_APPWINDOW|WS_EX_CONTROLPARENT,wc.lpszClassName,L"TidyDesk 设置",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,r.right-r.left,r.bottom-r.top,owner,nullptr,wc.hInstance,nullptr);ShowWindow(page,SW_SHOW);SetForegroundWindow(page);}
void SettingsStatus(const wchar_t* text){backendStatus=text;if(page&&!dirty&&!applying&&(awaitingTaskbar||active==0)){Status(text);if(backendStatus.find(L"应用成功")==0||backendStatus.find(L"应用失败")==0)awaitingTaskbar=false;if(backendStatus.find(L"应用失败")==0)EnableWindow(GetDlgItem(page,300),TRUE);}}
void CloseSettings(){if(page)DestroyWindow(page);}
bool SettingsMessage(MSG* m){return page&&IsDialogMessageW(page,m);}

int TestSettings(){
 const std::wstring testKey=L"Software\\TidyDesk.SettingsTest."+std::to_wstring(GetCurrentProcessId());Key=testKey.c_str();Put(L"Migrated",1);Put(L"Opacity",7);Put(L"Maximized",0);Put(L"Theme",1);int result=0;
 ShowSettings(nullptr,{});boxes.clear();SendDlgItemMessageW(page,12,TBM_SETPOS,TRUE,42);SendMessageW(page,WM_HSCROLL,TB_THUMBPOSITION,reinterpret_cast<LPARAM>(GetDlgItem(page,12)));CheckDlgButton(page,13,BST_CHECKED);SendMessageW(page,WM_COMMAND,13,0);
 if(Get(L"Opacity",0)!=7||Get(L"Maximized",0)!=0)result=1;
 SendMessageW(page,WM_COMMAND,102,0);if(draft.opacity!=42||!draft.maximized)result=2;
 CloseSettings();if(Get(L"Opacity",0)!=7||Get(L"Maximized",0)!=0)result=3;
 ShowSettings(nullptr,{});boxes.clear();SendMessageW(page,WM_COMMAND,100,0);SendDlgItemMessageW(page,12,TBM_SETPOS,TRUE,42);SendMessageW(page,WM_HSCROLL,TB_THUMBPOSITION,reinterpret_cast<LPARAM>(GetDlgItem(page,12)));CheckDlgButton(page,13,BST_CHECKED);SendMessageW(page,WM_COMMAND,13,0);Put(L"Desktop",1);SendMessageW(page,WM_COMMAND,300,0);if(Get(L"Opacity",0)!=42||Get(L"Maximized",0)!=1||Get(L"Desktop",0)!=1)result=4;Put(L"Desktop",0);draft.desktop=false;appliedDraft.desktop=false;
 SendMessageW(page,WM_COMMAND,103,0);SendDlgItemMessageW(page,240,CB_SETCURSEL,2,0);SendMessageW(page,WM_COMMAND,MAKEWPARAM(240,CBN_SELCHANGE),0);if(Get(L"Theme",0)!=1||draft.theme!=2)result=7;SendMessageW(page,WM_COMMAND,300,0);if(Get(L"Theme",0)!=2)result=8;
 SettingsStatus(L"应用成功");
 // Render the actual native controls for visual review, not a separate HTML mock.
 ULONG_PTR token=0;Gdiplus::GdiplusStartupInput input;Gdiplus::GdiplusStartup(&token,&input,nullptr);CLSID png{0x557cf406,0x1a04,0x11d3,{0x9a,0x73,0x00,0x00,0xf8,0x1e,0xf3,0x2e}};
 for(unsigned theme:{1U,2U}){Put(L"Theme",theme);draft.theme=theme;appliedDraft.theme=theme;for(int index=0;index<4;++index){active=index;Build();if(GetDlgItem(page,210)||GetDlgItem(page,211)||(index==1&&(!GetDlgItem(page,215)||GetDlgItem(page,92))))result=6;UpdateWindow(page);RECT r{};GetClientRect(page,&r);HDC dc=GetDC(page),memory=CreateCompatibleDC(dc);HBITMAP image=CreateCompatibleBitmap(dc,r.right,r.bottom);auto old=SelectObject(memory,image);PrintWindow(page,memory,PW_CLIENTONLY);{Gdiplus::Bitmap bitmap(image,nullptr);auto filename=L"settings-"+std::to_wstring(index)+(theme==1?L"-light.png":L"-dark.png");if(bitmap.Save(filename.c_str(),&png,nullptr)!=Gdiplus::Ok)result=5;}SelectObject(memory,old);DeleteObject(image);DeleteDC(memory);ReleaseDC(page,dc);}}
 Gdiplus::GdiplusShutdown(token);CloseSettings();RegDeleteTreeW(HKEY_CURRENT_USER,testKey.c_str());Key=L"Software\\TidyDesk";return result;
}
